// ============================================================
// N'Eye Vocab - DATA FILE
// อัพเดทศัพท์รายวันแก้ที่ไฟล์นี้ที่เดียว (ไม่ต้องแตะ index.html)
//  VOCAB         [en, th, synonym]  -> การ์ด/ควิซ/จับคู่
//  NEW_SENTENCES [ประโยค, คำตอบ, คำใบ้, [ตัวเลือก4], ระดับ0-3] -> แบบฝึกเติมคำ
//  EXAMS.dayN    -> บทติวสอบวันใหม่
// ============================================================

const VOCAB = [
["Consonant","พยัญชนะ","letter (not a e i o u)"],
["Vowel","สระ","a e i o u"],
["Colleague","เพื่อนร่วมงาน","co-worker"],
["Ambiguous","คลุมเครือ ไม่ชัดเจน","unclear, vague"],
["Approach","เข้าใกล้ / เข้าหา","come near"],
["Scold","ดุ, ด่า","tell off"],
["Certain","มั่นใจ, แน่นอน","sure, definite"],
["Sighting","การพบเห็น (สิ่งแปลกๆ)","seeing something"],
["Saucer","จานรอง / จานบิน","small plate; UFO"],
["Moderate","ปานกลาง","average, medium"],
["Struck","ชน, กระแทก","hit (past of strike)"],
["Remain","คงเหลือ, ยังอยู่","stay, be left"],
["Evidence","หลักฐาน","proof"],
["Experiment","การทดลอง","test, trial"],
["Conclusion","บทสรุป","ending, summary"],
["Exist","มีอยู่, ดำรงอยู่","be, live"],
["Continent","ทวีป","landmass"],
["Crowded","แออัด คนเยอะ","packed, full"],
["Etiquette","มารยาท","manners"],
["Defamation","การหมิ่นประมาท","libel, slander"],
["Sue","ฟ้องร้อง","take to court"],
["Dignity","ศักดิ์ศรี","self-respect"],
["Depression","ภาวะซึมเศร้า","deep sadness"],
["Anxiety","ความวิตกกังวล","worry, nervousness"],
["Fiery","เผ็ดร้อน / ร้อนแรง","spicy, burning"],
["Various","หลากหลาย","many kinds, diverse"],
["Bland","จืดชืด ไม่มีรสชาติ","tasteless, plain"],
["Decade","ทศวรรษ (10 ปี)","ten years"],
["Contain","บรรจุ, มี...อยู่ข้างใน","hold, include"],
["Flu","ไข้หวัดใหญ่","influenza"],
["Barely","แทบจะไม่","hardly, almost not"],
["Cub","ลูกสัตว์","baby animal"],
["Curious","สงสัย อยากรู้","want to know"],
["Independent","เป็นอิสระ พึ่งตัวเอง","free, self-reliant"],
["Sacrifice","เสียสละ","give up for others"],
["Struggle","ดิ้นรน, ต่อสู้","fight, try hard"],
["Elderly","ผู้สูงอายุ","old people, seniors"],
["Wit","ไหวพริบ ความฉลาด","cleverness"],
["Athlete","นักกีฬา","sports player"],
["Tummy","ท้อง (คำน่ารัก)","stomach, belly"],
["Bandage","ผ้าพันแผล","plaster, dressing"],
["Tablet","ยาเม็ด","pill"],
["Fabric softener","น้ำยาปรับผ้านุ่ม","makes clothes soft"],
["Laundry detergent","ผงซักฟอก","washing powder"],
["Mature","เป็นผู้ใหญ่ มีความรับผิดชอบ","grown-up, responsible"],
["Tease","แกล้ง, ล้อเลียน","make fun of"],
["Impeccable","ไร้ที่ติ สมบูรณ์แบบ","perfect, flawless"],
["Inherit","รับมรดก, สืบทอด","receive from family"],
["Tense","เครียด, ตึงเครียด","nervous, stressed"],
["Swallow","กลืน","gulp down"],
["Punctual","ตรงต่อเวลา","on time"],
["Humor","อารมณ์ขัน","funny sense"],
["Believe","เชื่อ","think it's true"],
["Contrast","เปรียบเทียบความแตกต่าง","compare differences"],
["Control","ควบคุม","manage, rule"],
["Depend","พึ่งพา","rely on"],
["Duty","หน้าที่","responsibility, task"],
["Important","สำคัญ","significant, necessary"],
["Ordinary","ธรรมดา","normal, common"],
["Personality","บุคลิกภาพ","character"],
["Talkative","ช่างพูด","talks a lot, chatty"],
["Worry","กังวล","be anxious"],
["Annual","ประจำปี","every year, yearly"],
["Attempt","พยายาม","try"],
["Communicate","สื่อสาร","share information"],
["Emotional","มีอารมณ์ร่วม ซาบซึ้ง","full of feeling"],
["Gathering","งานรวมตัว ปาร์ตี้","party, meeting"],
["Maintain","รักษาไว้ ดูแลต่อเนื่อง","keep up, continue"],
["Provide","จัดหาให้","supply, give"],
["Reunion","งานพบปะคนที่ไม่เจอกันนาน","meeting again"],
["Terrific","เยี่ยมมาก","excellent, great"],
["Threaten","ขู่","warn to harm"],
["Affordable","ราคาจับต้องได้","cheap enough"],
["Bargain","ของราคาถูกกว่าจริง / ต่อรอง","good deal"],
["Boutique","ร้านแฟชั่นเล็กๆ มีสไตล์","small fashion shop"],
["Brand","แบรนด์ ยี่ห้อ","product name"],
["Choice","ตัวเลือก","option"],
["Customer","ลูกค้า","buyer, client"],
["Design","ลวดลาย การออกแบบ","pattern, style"],
["Imported","นำเข้าจากต่างประเทศ","from another country"],
["Purchase","ซื้อ","buy"],
["Shop","เดินซื้อของ","go buying"],
["Bored","เบื่อ","not interested"],
["Bother","รบกวน กวนใจ","annoy"],
["Character","นิสัย ตัวตน","personality, nature"],
["Free time","เวลาว่าง","leisure time"],
["Habit","สิ่งที่ทำเป็นประจำ","regular behavior"],
["Interesting","น่าสนใจ","catches attention"],
["Routine","กิจวัตร","regular way of doing"],
["Satisfy","ทำให้พอใจ","please, make happy"],
["Secret","ความลับ","hidden thing"],
["Transform","เปลี่ยนแปลงโดยสิ้นเชิง","change completely"],
["Adventure","การผจญภัย","exciting journey"],
["Book (v.)","จอง (ตั๋ว/โรงแรม)","reserve"],
["Cruise","ล่องเรือเที่ยว","pleasure voyage"],
["Haste","ความรีบร้อน","hurry, rush"],
["Impressive","น่าประทับใจ","admirable, amazing"],
["Itinerary","แผนการเดินทาง","travel plan"],
["Native","พื้นเมือง ท้องถิ่น","original to a place"],
["Scenery","ทิวทัศน์","view, landscape"],
["Brochure","แผ่นพับ โบรชัวร์","booklet, pamphlet"],
["Transportation","การเดินทางขนส่ง","way of traveling"],
["Grain","ธัญพืช เมล็ดพืช","seeds for food"],
["Compose","ประกอบขึ้นเป็น","form, make up"],
["Luxurious","หรูหรา","fancy, costly"],
["Fast food","อาหารจานด่วน","quick cheap meal"],
["Spicy","เผ็ด","hot taste"],
["Unhealthy","ไม่ดีต่อสุขภาพ","bad for health"],
["Chef","เชฟ พ่อครัวมืออาชีพ","professional cook"],
["Boost","กระตุ้น เสริม","support, improve"],
["Nutritious","มีคุณค่าทางอาหาร","nourishing, healthy"],
["Carbohydrate","คาร์โบไฮเดรต แป้ง","starch, sugar"],
["Instrument","เครื่องดนตรี","musical device"],
["Lyrics","เนื้อเพลง","words of a song"],
["Idol","ไอดอล คนที่คลั่งไคล้","someone adored"],
["Tune","ทำนอง","melody"],
["Rhythm","จังหวะ","beat"],
["Download","ดาวน์โหลด","copy from internet"],
["Classic","คลาสสิก ระดับตำนาน","timeless, top quality"],
["Soothing","ผ่อนคลาย ชวนสงบ","calming, gentle"],
["Emotion","อารมณ์ความรู้สึก","feeling"],
["Melody","ท่วงทำนอง","tune, notes"],
["Impression","ความรู้สึกแรก ความประทับใจ","feeling, idea"],
["Conquer","พิชิต ยึดครอง","defeat, take over"],
["Credit","เครดิต การอ้างอิงแหล่งที่มา","recognition note"],
["Conclude","สรุป ตัดสินใจจากเหตุผล","decide, sum up"],
["Setting","ฉาก (เวลา+สถานที่ของเรื่อง)","time & place of a story"],
["Genre","ประเภท แนว (หนัง/เพลง/หนังสือ)","category, type"],
["Theatre","โรงภาพยนตร์ โรงละคร","cinema, playhouse"],
["Effects","เทคนิคพิเศษ แสง สี เสียง","special effects"],
["Sci-fi","นิยายวิทยาศาสตร์","science fiction"],
["Thriller","แนวระทึกขวัญ","suspense story"],
["Opinion","ความคิดเห็น","view, judgment"],
["Site","สถานที่ก่อสร้าง / ที่ตั้ง","location, area"],
["Hangout","ที่ที่ไปประจำ","favorite place"],
["Skip","โดด(เรียน) ข้าม","miss, not attend"],
["Regularly","เป็นประจำ สม่ำเสมอ","at regular times"],
["Hobby","งานอดิเรก","leisure activity"],
["Couch","โซฟา","sofa"],
["Collection","ของสะสม การสะสม","collected things"],
["Decide","ตัดสินใจ","make a decision"],
["Frequent","ไปบ่อยๆ","visit often"],
["Abstract","นามธรรม จับต้องไม่ได้","idea, not physical"],
["Expressive","แสดงความรู้สึกได้ดี","showing feeling"],
["Showcase","จัดแสดง โชว์","exhibit, display"],
["Culture","วัฒนธรรม","customs, arts"],
["Creation","ผลงานสร้างสรรค์","something made"],
["Extraordinary","พิเศษเหนือธรรมดา","remarkable, unusual"],
["Canvas","ภาพวาดสีน้ำมัน / ผ้าใบ","oil painting"],
["Unique","มีหนึ่งเดียว ไม่เหมือนใคร","one of a kind"],
["Visual","มองเห็นได้ด้วยตา","seen by the eye"],
["Masterpiece","ผลงานชิ้นเอก","great work"],
// ---- เพิ่มชุดใหม่ ----
["Suspect","สงสัย / ผู้ต้องสงสัย","think guilty; doubt"],
["Recurring","เกิดขึ้นซ้ำๆ","happening again"],
["Predictions","คำทำนาย การคาดการณ์","forecasts, guesses"],
["Insomnia","โรคนอนไม่หลับ","sleeplessness"],
["Consciousness","การมีสติ ความรู้สึกตัว","awareness"],
["Numerous","จำนวนมาก มากมาย","many, countless"],
["Aspects","แง่มุม ด้านต่างๆ","sides, angles"],
["Hedonism","ลัทธิสุขนิยม เน้นความสำราญ","pleasure-seeking"],
["Define","ให้คำนิยาม กำหนดความหมาย","explain meaning"],
["Disaster","ภัยพิบัติ หายนะ","catastrophe"],
["Counterintuitive","ขัดกับสามัญสำนึก","against common sense"],
["Stagnant","หยุดนิ่ง ไม่เติบโต","not moving, still"],
["Suppressant","ตัวยับยั้ง สารกด","something that reduces"],
["Widening","การขยายให้กว้างขึ้น","making wider"],
["Vulnerable","เปราะบาง ถูกทำร้ายง่าย","easily hurt, weak"],
["Recede","ถอยห่าง ค่อยๆ ลดลง","move back, fade"],
["Unduly","มากเกินควร เกินกว่าเหตุ","excessively"],
["Premises","สถานที่ อาคารและที่ดิน","building & land"],
["Gratitude","ความรู้สึกขอบคุณ ความกตัญญู","thankfulness"],
["Contribute","มีส่วนร่วม ช่วยสนับสนุน","give, add to"],
["Cultivate","บ่มเพาะ พัฒนา / เพาะปลูก","grow, develop"],
["Heritage","มรดกทางวัฒนธรรม","tradition, legacy"],
["Hunter-gatherers","มนุษย์ยุคล่าสัตว์เก็บของป่า","early food-finding people"],
["Venting","การระบายอารมณ์ / ระบายอากาศ","letting out feelings"],
["Accompanied","มาพร้อมกับ ไปเป็นเพื่อน","went with"],
["Accomplishment","ความสำเร็จ ผลงาน","achievement"],
["Retrieval","การเรียกคืน การดึงกลับมา","getting back"],
["Capable","มีความสามารถ ทำได้","able, skilled"],
["Miserable","ทุกข์ระทม เศร้าหมองมาก","very unhappy"],
["Defy","ท้าทาย ฝ่าฝืน ขัดขืน","resist, disobey"],
["Greater","มากกว่า ยิ่งใหญ่กว่า","bigger, more"],
["Retrieve","เอากลับคืนมา ดึงกลับ","get back, fetch"],
["Owes","เป็นหนี้ ติดค้าง","must pay back"],
["Pursue","ไล่ตาม มุ่งมั่นทำต่อ","chase, go after"],
["Euthanasia","การุณยฆาต ช่วยให้ตายอย่างสงบ","mercy killing"],
["Burden","ภาระ สิ่งที่หนักอึ้ง","heavy load"],
["Misused","ใช้ผิดวิธี ใช้ในทางที่ผิด","used wrongly"],
["Against","ต่อต้าน / พิงกับ","opposed to"],
["Waiver","การสละสิทธิ์ / เอกสารสละสิทธิ์","giving up a right"],
["Agonizing","เจ็บปวดทรมานมาก","very painful"],
["Guilty","รู้สึกผิด / มีความผิด","feeling of doing wrong"],
["Exhausted","เหนื่อยล้าหมดแรง","very tired"],
["Bond","ความผูกพัน / พันธะ","close connection"],
["Itchy","คัน","wanting to scratch"],
["Allergy","อาการแพ้","bad body reaction"],
["Diphthong","สระประสม เสียงสระควบ","two-vowel sound"],
["Resource","ทรัพยากร แหล่งทรัพยากร","supply, asset"],
["Assume","สันนิษฐาน คิดเอาเอง","suppose, guess"],
["Possession","การครอบครอง สิ่งที่เป็นเจ้าของ","owning; belongings"],
["Conviction","ความเชื่อมั่นแรงกล้า / การตัดสินว่าผิด","strong belief"],
["Compassion","ความเห็นอกเห็นใจ ความเมตตา","kindness, sympathy"],
["Integrity","ความซื่อสัตย์ มีคุณธรรม","honesty, strong morals"],
["Diligence","ความขยันหมั่นเพียร","hard work, care"],
["Foresight","การมองการณ์ไกล","planning ahead"],
["Overwhelmed","ท่วมท้น รับมือไม่ไหว","flooded, overloaded"],
// ---- Day 11-13 (Beginner) ----
["Apologize","ขอโทษ กล่าวคำขอโทษ","say sorry"],
["Annoy","ทำให้รำคาญ กวนใจ","irritate, bother"],
["React","ตอบสนอง แสดงปฏิกิริยา","respond"],
["Occasion","โอกาส วาระพิเศษ งานสำคัญ","special event"],
["Mingle","เดินทักทายเข้าสังคม พูดคุยปะปน","socialize, mix"],
["Unexpected","ไม่คาดคิด เหนือความคาดหมาย","surprising, unforeseen"],
["Outcast","คนนอกคอก คนที่ถูกสังคมกีดกัน","rejected person"],
["Affair","เรื่องราว เหตุการณ์","event, matter"],
["Absorb","ซึมซับ รับเข้าไป (ข้อมูล/ความรู้)","take in"],
["Refuse","ปฏิเสธ ไม่ยอม","decline, reject"],
["Excuse","ข้อแก้ตัว เหตุผลแก้ตัว","reason, justification"],
["Insult","คำดูถูก การสบประมาท","offensive remark"],
["Injury","การบาดเจ็บ ความเสียหาย","harm, damage"],
["Irritation","ความรำคาญ การระคายเคือง","annoyance"],
["Particular","เฉพาะเจาะจง โดยเฉพาะ","specific"],
["Noteworthy","น่าสังเกต น่าจดจำ","remarkable"],
["Assimilate","ซึมซับกลืนเป็นของตน ทำความเข้าใจ","absorb, take in"],
["Sunscreen","ครีมกันแดด","sunblock"],
["Sandcastle","ปราสาททราย","sand model"],
["Temperature","อุณหภูมิ","degree of heat/cold"],
["Tropical","เขตร้อน แบบเมืองร้อน","hot-climate"],
["Sunburn","ผิวไหม้แดด","sun-damaged skin"],
["Desire","ความปรารถนา ความอยาก","strong wish"],
["Vacation","วันหยุดพักผ่อน การไปเที่ยว","holiday"],
["Entertain","ต้อนรับเลี้ยงดูแขก / ให้ความบันเทิง","host, amuse"],
["Wander","เดินเตร่ ท่องไปเรื่อย","roam"],
["Dive","กระโดดหัวปักลงน้ำ ดำน้ำ","plunge"],
["Theoretically","ตามทฤษฎี ในทางทฤษฎี","in theory"],
["Reddening","การกลายเป็นสีแดง (ผิวแดง)","turning red"],
["Overexposure","การโดน(แดด)มากเกินไป","too much exposure"],
["Blistering","การเกิดตุ่มพอง","forming blisters"],
["Peeling","การลอก (ผิวลอก)","coming off in layers"],
["Inflammation","การอักเสบ บวมแดง","swelling, soreness"],
["Definite","แน่นอน ชัดเจน","clear, fixed"],
["Aimlessly","อย่างไร้จุดหมาย","without purpose"],
["Forecast","การพยากรณ์ คำทำนาย (อากาศ/แนวโน้ม)","prediction"],
["Region","ภูมิภาค เขตพื้นที่","area, zone"],
["Fireplace","เตาผิง","hearth"],
["Avalanche","หิมะถล่ม","snowslide"],
["Snowball","ก้อนหิมะ (ปั้นขว้าง)","packed snow ball"],
["Elevated","ยกสูงขึ้น อยู่สูง","raised"],
["Sled","เลื่อนหิมะ","snow vehicle"],
["Twigs","กิ่งไม้เล็กๆ","small branches"],
["Scarf","ผ้าพันคอ","neck cloth"],
["Snowboard","กระดานเล่นหิมะ","snow board"],
["Chimney","ปล่องไฟ","smoke pipe"],
["Rapidly","อย่างรวดเร็ว","quickly, fast"],
["Conveying","การขนส่ง ลำเลียง","carrying, transporting"],
["Slender","เรียว บาง","slim, thin"],
["Branch","กิ่งก้าน (ของต้นไม้)","tree limb"],
["Shrub","ไม้พุ่ม","bush"],
["Resembling","คล้ายกับ ดูเหมือน","looking like"],
["Nonchalant","เฉยเมย ไม่รู้ร้อนรู้หนาว วางเฉย","calm, unbothered"],
["Mandatory","ที่บังคับ ต้องทำตามข้อกำหนด","required, compulsory"],
["Bribe","สินบน / ติดสินบน","illegal payment"]
];

const SENTENCES = [
// 1-10 Beginner
["She drinks coffee every morning before work. It is her daily ___.","Habit","สิ่งที่ทำประจำ",["Habit","Hobby","Duty","Choice"]],
["The little boy fell down, so the nurse put a ___ on his knee.","Bandage","ปิดแผลที่เข่า",["Bandage","Tablet","Bottle","Napkin"]],
["My ___ is full — I can't eat any more cake!","Tummy","อิ่มมากแล้ว",["Tummy","Elbow","Shoulder","Ankle"]],
["He plays three musical ___: piano, guitar, and drums.","Instruments","เปียโน กีตาร์ กลอง คือ...",["Instruments","Melodies","Lyrics","Rhythms"]],
["Tom Yum soup is too ___ for my little brother.","Spicy","น้องกินเผ็ดไม่ได้",["Spicy","Bland","Sweet","Cold"]],
["The mother bear watched her ___ playing in the snow.","Cub","ลูกของหมีเรียกว่า...",["Cub","Calf","Chick","Puppy"]],
["I ___ the new song to my phone so I can listen offline.","Downloaded","เอาเพลงจากเน็ตลงเครื่อง",["Downloaded","Uploaded","Printed","Deleted"]],
["Sarah is my ___ — we sit next to each other at the office.","Colleague","คนที่ทำงานด้วยกัน",["Colleague","Customer","Neighbor","Cousin"]],
["Africa is a large ___ with 54 countries.","Continent","ใหญ่กว่าประเทศ",["Continent","Country","Island","Ocean"]],
["Reading comic books is my favorite ___ on weekends.","Hobby","ทำตอนว่างเพื่อความสนุก",["Hobby","Habit","Duty","Job"]],
// 11-20 Normal
["The morning train was so ___ that people were pushing to get in.","Crowded","คนแน่นจนต้องเบียด",["Crowded","Narrow","Noisy","Busy"]],
["Everyone trusts him with meetings because he is always ___.","Punctual","ไม่เคยมาสาย",["Punctual","Talkative","Curious","Generous"]],
["Check the ___ — I think we visit the temple before lunch, not after.","Itinerary","เอกสารบอกแผนเที่ยว",["Itinerary","Brochure","Passport","Ticket"]],
["Regular exercise can ___ your energy during the day.","Boost","ทำให้พลังงานเพิ่มขึ้น",["Boost","Maintain","Control","Measure"]],
["The police cannot arrest him — there is not enough ___.","Evidence","สิ่งที่ใช้พิสูจน์ความผิด",["Evidence","Opinion","Rumor","News"]],
["When his aunt passed away, he ___ her old house by the river.","Inherited","ได้รับต่อจากญาติที่เสียชีวิต",["Inherited","Purchased","Rented","Borrowed"]],
["Bangkok has many kinds of public ___: buses, boats, and trains.","Transportation","รถเมล์ เรือ รถไฟ คือ...",["Transportation","Communication","Construction","Information"]],
["Stop ___ your sister about her new haircut — she's getting upset.","Teasing","ล้อจนเขาจะร้องไห้",["Teasing","Praising","Helping","Watching"]],
["Brown rice is more ___ than white rice.","Nutritious","ดีต่อร่างกายมากกว่า",["Nutritious","Delicious","Expensive","Popular"]],
["We are planning a family ___ because we haven't met for five years.","Reunion","กลับมาเจอกันหลังห่างหายไปนาน",["Reunion","Meeting","Vacation","Ceremony"]],
// 21-30 Hard
["Despite the argument, both companies want to ___ their business relationship.","Maintain","รักษาความสัมพันธ์ไว้ต่อ",["Maintain","Conclude","Attempt","Threaten"]],
["The politician gave an ___ answer, so reporters kept asking the same question.","Ambiguous","ตอบแบบตีความได้หลายทาง",["Ambiguous","Impressive","Emotional","Impeccable"]],
["After the operation, grandpa could ___ walk without help.","Barely","เกือบจะเดินไม่ได้เลย",["Barely","Slowly","Safely","Bravely"]],
["The actress decided to ___ the magazine for printing false stories about her.","Sue","ดำเนินคดีทางกฎหมาย",["Sue","Scold","Blame","Warn"]],
["It took her years to ___ her fear of speaking in public.","Overcome","ก้าวข้ามความกลัว",["Overcome","Maintain","Express","Admit"]],
["The film won an award for its stunning visual ___.","Effects","CG แสง สี ในหนัง",["Effects","Settings","Credits","Genres"]],
["You can recognize her paintings immediately — her style is very ___.","Distinctive","เห็นปุ๊บรู้เลยว่าของเธอ",["Distinctive","Ordinary","Ambiguous","Traditional"]],
["Good comedy needs perfect timing and sharp ___.","Wit","ความฉลาดแบบเร็วๆ",["Wit","Emotion","Dignity","Courage"]],
["The director changed the ___ of the play from London to Bangkok.","Setting","เวลาและสถานที่ของเรื่อง",["Setting","Plot","Genre","Audience"]],
["Small daily savings, done ___, can grow into a large amount.","Regularly","ทำสม่ำเสมอไม่ขาด",["Regularly","Barely","Suddenly","Recently"]],
// 31-40 Native
["Even after losing everything, the old man never lost his ___.","Dignity","ความภูมิใจในตัวเอง",["Dignity","Fortune","Memory","Balance"]],
["The novel ___ life in rural Thailand with honesty and warmth.","Portrays","วาดภาพ/ถ่ายทอดเรื่องราว",["Portrays","Maintains","Concludes","Inherits"]],
["Critics praised the film's complex ___, full of unexpected twists.","Plot","เนื้อเรื่องตั้งแต่ต้นจนจบ",["Plot","Setting","Genre","Theatre"]],
["During the Cold War, both sides used ___ to steal military secrets.","Espionage","งานของสายลับ",["Espionage","Defamation","Diplomacy","Propaganda"]],
["A good soundtrack can greatly ___ the emotional impact of a scene.","Enhance","ทำให้ดียิ่งขึ้นไปอีก",["Enhance","Replace","Disturb","Follow"]],
["Her manners were ___ — every guest felt perfectly welcomed.","Impeccable","ไม่มีอะไรให้ติเลย",["Impeccable","Adequate","Casual","Familiar"]],
["From the fingerprints on the glass, the detective ___ that the thief was left-handed.","Concluded","ใช้เหตุผลจากหลักฐานแล้วตัดสิน",["Concluded","Suspected","Announced","Denied"]],
["Moving out at eighteen taught her to be financially ___.","Independent","ดูแลตัวเองไม่พึ่งใคร",["Independent","Confident","Generous","Ambitious"]],
["Many consider this temple the ___ of Ayutthaya-period architecture.","Masterpiece","ผลงานที่ดีที่สุดของยุค",["Masterpiece","Collection","Creation","Monument"]],
["In her ___ to reply to the angry email, she forgot to check the attachment.","Haste","รีบจนพลาด",["Haste","Effort","Delay","Silence"]]
];

const NEW_SENTENCES=[
["Can you ___ this word for me? I don't know what it means.","Define","บอกความหมาย",["Define","Design","Divide","Deny"],0],
["The flood was a terrible ___ that destroyed many homes.","Disaster","ภัยพิบัติร้ายแรง",["Disaster","Adventure","Ceremony","Journey"],0],
["Ten is ___ than five.","Greater","มากกว่า",["Greater","Smaller","Equal","Fewer"],0],
["The team played ___ their biggest rivals last night.","Against","แข่งกับ / ต่อต้าน",["Against","Beside","Toward","Among"],0],
["He felt ___ after eating his sister's cake without asking.","Guilty","รู้สึกผิด",["Guilty","Proud","Happy","Calm"],0],
["The wool sweater makes my skin ___.","Itchy","คันผิว",["Itchy","Silky","Warm","Dry"],0],
["She can't eat peanuts because she has an ___.","Allergy","อาการแพ้",["Allergy","Injury","Energy","Ability"],0],
["The strong ___ between the twins never broke.","Bond","ความผูกพัน",["Bond","Gap","Fight","Rule"],0],
["After the marathon, the runners were completely ___.","Exhausted","เหนื่อยหมดแรง",["Exhausted","Energetic","Excited","Relaxed"],0],
["Don't ___ he is angry just because he is quiet.","Assume","คิดไปเอง / สันนิษฐาน",["Assume","Prove","Announce","Forget"],0],
["Water is a precious natural ___.","Resource","ทรัพยากร",["Resource","Response","Reason","Result"],0],
["There are ___ reasons to learn English.","Numerous","จำนวนมาก",["Numerous","Rare","Single","Few"],0],
["The police ___ that he stole the car, but they have no proof yet.","Suspect","สงสัยว่าผิด",["Suspect","Confirm","Forgive","Ignore"],1],
["She has a ___ dream about flying over the ocean.","Recurring","เกิดขึ้นซ้ำๆ",["Recurring","Single","Final","Sudden"],1],
["The weather ___ said it would rain, but the sky is clear.","Predictions","การคาดการณ์",["Predictions","Memories","Directions","Decisions"],1],
["We must consider all ___ of the problem before deciding.","Aspects","แง่มุมต่างๆ",["Aspects","Answers","Amounts","Objects"],1],
["She is a ___ leader who can handle any crisis.","Capable","มีความสามารถ",["Capable","Careless","Nervous","Ordinary"],1],
["The cold, rainy weather made everyone feel ___.","Miserable","ทุกข์เศร้าหมอง",["Miserable","Cheerful","Grateful","Curious"],1],
["Taking care of the whole family became a heavy ___ for her.","Burden","ภาระอันหนัก",["Burden","Blessing","Bargain","Balance"],1],
["He still ___ me the money I lent him last month.","Owes","เป็นหนี้ / ติดค้าง",["Owes","Owns","Offers","Orders"],1],
["She decided to ___ a career in medicine.","Pursue","มุ่งมั่นไล่ตาม",["Pursue","Avoid","Pause","Refuse"],1],
["Everyone should ___ some ideas to the group project.","Contribute","มีส่วนร่วม / ช่วย",["Contribute","Consume","Compete","Complain"],1],
["She wrote a letter to express her ___ to her teacher.","Gratitude","ความรู้สึกขอบคุณ",["Gratitude","Attitude","Jealousy","Regret"],1],
["The child was ___ by her mother at the hospital.","Accompanied","ไปเป็นเพื่อน / มาพร้อม",["Accompanied","Abandoned","Confused","Replaced"],1],
["Finishing the marathon was a great ___ for him.","Accomplishment","ความสำเร็จ",["Accomplishment","Assignment","Appointment","Arrangement"],1],
["The old watch is his most valuable ___.","Possession","สิ่งที่ครอบครอง",["Possession","Profession","Position","Permission"],1],
["She felt ___ by the huge amount of homework.","Overwhelmed","ท่วมท้นรับไม่ไหว",["Overwhelmed","Underpaid","Relieved","Prepared"],1],
["The government is ___ the road to reduce traffic.","Widening","ทำให้กว้างขึ้น",["Widening","Closing","Cleaning","Crossing"],1],
["He called his best friend, ___ his anger about work.","Venting","ระบายอารมณ์",["Venting","Hiding","Solving","Praising"],1],
["Her ___ keeps her awake until three in the morning.","Insomnia","นอนไม่หลับ",["Insomnia","Ambition","Allergy","Amnesia"],2],
["The boxer lost ___ after the powerful punch.","Consciousness","การรู้สึกตัว / สติ",["Consciousness","Confidence","Conviction","Conclusion"],2],
["Without a strong password, your account is ___ to hackers.","Vulnerable","เปราะบาง / ถูกโจมตีง่าย",["Vulnerable","Valuable","Reliable","Comfortable"],2],
["The company's sales have been ___ for three years — no growth at all.","Stagnant","หยุดนิ่งไม่โต",["Stagnant","Booming","Flexible","Sudden"],2],
["As the tide began to ___, the children built sandcastles.","Recede","ถอยลดลง",["Recede","Rise","Return","Repeat"],2],
["It takes years to ___ a good habit of reading.","Cultivate","บ่มเพาะ / พัฒนา",["Cultivate","Cancel","Copy","Consume"],2],
["The ancient temple is part of our national ___.","Heritage","มรดกทางวัฒนธรรม",["Heritage","Property","Territory","Ceremony"],2],
["The ___ of deleted files is sometimes impossible.","Retrieval","การเรียกคืน",["Retrieval","Removal","Refusal","Renewal"],2],
["The dog was trained to ___ the ball and bring it back.","Retrieve","เอากลับคืนมา",["Retrieve","Release","Receive","Refuse"],2],
["The brave workers chose to ___ their cruel boss's unfair orders.","Defy","ฝ่าฝืน / ขัดขืน",["Defy","Obey","Deny","Delay"],2],
["The funds were ___ and spent on personal luxuries.","Misused","ใช้ในทางที่ผิด",["Misused","Refunded","Donated","Collected"],2],
["The nurse treated every patient with warmth and ___.","Compassion","ความเห็นอกเห็นใจ",["Compassion","Ambition","Confusion","Suspicion"],2],
["A leader with ___ never lies to the people.","Integrity","ความซื่อสัตย์มีคุณธรรม",["Integrity","Popularity","Authority","Curiosity"],2],
["Through hard work and ___, she passed the difficult exam.","Diligence","ความขยันหมั่นเพียร",["Diligence","Laziness","Luck","Talent"],2],
["Thanks to his ___, the company saved money before the crisis.","Foresight","การมองการณ์ไกล",["Foresight","Hindsight","Eyesight","Delight"],2],
["She spoke with such ___ that everyone believed her.","Conviction","ความเชื่อมั่นแรงกล้า",["Conviction","Confusion","Hesitation","Description"],2],
["Smoking is not allowed anywhere on the company ___.","Premises","สถานที่ / อาคาร",["Premises","Promises","Premiums","Passengers"],2],
["His life of pure ___ was all about parties, pleasure, and no responsibility.","Hedonism","ใช้ชีวิตเน้นความสำราญ",["Hedonism","Heroism","Idealism","Realism"],3],
["It seems ___, but eating fat does not always make you fat.","Counterintuitive","ขัดกับที่คนทั่วไปคิด",["Counterintuitive","Straightforward","Predictable","Reasonable"],3],
["The doctor prescribed an appetite ___ to help him lose weight.","Suppressant","ตัวกด / ยับยั้ง",["Suppressant","Supplement","Statement","Instrument"],3],
["She was ___ worried about a test she had clearly prepared for.","Unduly","มากเกินกว่าเหตุ",["Unduly","Barely","Rarely","Fairly"],3],
["Before farming, ___ survived by hunting animals and picking wild plants.","Hunter-gatherers","มนุษย์ยุคล่าสัตว์เก็บของป่า",["Hunter-gatherers","Office-workers","City-dwellers","Factory-owners"],3],
["___ remains illegal in many countries because of ethical debate.","Euthanasia","การุณยฆาต",["Euthanasia","Anesthesia","Insomnia","Nostalgia"],3],
["Before skydiving, you must sign a ___ to release the company from blame.","Waiver","เอกสารสละสิทธิ์",["Waiver","Voucher","Receipt","License"],3],
["Waiting for the exam results was an ___ two weeks.","Agonizing","ทรมานเจ็บปวด",["Agonizing","Amusing","Relaxing","Rewarding"],3],
["The word 'coin' contains a ___ — two vowel sounds gliding together.","Diphthong","สระประสม",["Diphthong","Consonant","Syllable","Paragraph"],3]
];

const EXAMS = {
d8:{ name:"Day 8", banner:"หนัง ละคร วรรณกรรม",
main:[
["Impression","ความรู้สึกแรก ความประทับใจ (เกิดขึ้นเองโดยยังไม่มีหลักฐานมาก)","feeling, idea","I had an impression that she was lying."],
["Conquer","พิชิต ยึดครอง (ด้วยกำลัง)","defeat, take over","The Magyars conquered Hungary in the Middle Ages."],
["Credit","เครดิต ข้อความอ้างอิงแหล่งที่มา","recognition note","The credits are usually printed at the front of a book."],
["Conclude","สรุป ตัดสินใจโดยใช้เหตุผล","decide, sum up","We concluded that it was cheaper to rent than to buy a house."],
["Setting","ฉาก = เวลา+สถานที่ที่เรื่องเกิดขึ้น","time & place of a story","The setting of the novel is Paris in the 1920s."],
["Genre","ประเภท/แนวของงานศิลปะ เพลง หนัง หนังสือ","category, type","Horror and sci-fi are my favorite genres."],
["Theatre","โรงภาพยนตร์ โรงละคร","cinema, playhouse","I don't normally watch movies in the theatre."],
["Effects","เทคนิคพิเศษ แสง สี เสียง","special effects","Cool movies always have amazing sound effects."],
["Sci-fi","นิยายวิทยาศาสตร์ (อนาคต อวกาศ)","science fiction","Avatar is the best sci-fi movie for me."],
["Thriller","นิยาย/หนังระทึกขวัญ มักมีอาชญากรรม","suspense story","Children don't watch thriller movies."]
],
extra:[
["Conscious","รู้ตัว มีสติ","aware","without conscious thought = โดยไม่ทันรู้ตัว"],
["Evidence","หลักฐาน","proof","on the basis of little evidence = จากหลักฐานน้อยนิด"],
["Overcome","เอาชนะ ก้าวข้าม","defeat, get past","Conquer = overcome and take control"],
["Take control","เข้าควบคุม ยึดอำนาจ","take over","...take control of a place or people"],
["Reasoning","การใช้เหตุผล","logical thinking","Conclude = decide by reasoning"],
["Composition","งานประพันธ์ / การจัดองค์ประกอบ","artistic work","Genre = a category of artistic composition"],
["Distinctive","โดดเด่นเฉพาะตัว","special, unique style","marked by a distinctive style"],
["Audience","ผู้ชม คนดู","viewers, crowd","tiered seats for an audience"],
["Enhance","เสริมให้ดีขึ้น ยกระดับ","improve, upgrade","Effects enhance a stage, film, or broadcast"],
["Plot","โครงเรื่อง","storyline","A thriller has an exciting plot"],
["Espionage","การจารกรรม งานสายลับ","spying","Thriller involves crime or espionage"]
],
sent:[
["The ___ of the story is a small town in the 1980s.","Setting","เวลา+สถานที่ของเรื่อง",["Setting","Plot","Genre","Credit"]],
["The Romans ___ most of Europe two thousand years ago.","Conquered","ยึดครองด้วยกำลังทหาร",["Conquered","Concluded","Enhanced","Portrayed"]],
["From the muddy footprints, she ___ that someone had entered the house.","Concluded","ใช้เหตุผลจากร่องรอย",["Concluded","Suspected","Ignored","Announced"]],
["Romance is a popular ___ among teenagers.","Genre","แนว/ประเภทของหนังหรือหนังสือ",["Genre","Setting","Theatre","Effects"]],
["The magician's show used smoke and lighting ___.","Effects","เทคนิคพิเศษบนเวที",["Effects","Credits","Plots","Settings"]],
["The old ___ near my house shows classic films every Sunday.","Theatre","สถานที่ฉายหนัง",["Theatre","Site","Hangout","Couch"]],
["My first ___ of the new manager was that he was very strict.","Impression","ความรู้สึกแรกที่ได้เจอ",["Impression","Opinion","Evidence","Emotion"]],
["A good ___ keeps you guessing until the last page.","Thriller","แนวหนังสือที่ลุ้นระทึก",["Thriller","Credit","Audience","Composition"]],
["The ___ at the beginning of the film lists all the actors.","Credits","รายชื่อทีมงานในหนัง",["Credits","Effects","Settings","Genres"]],
["The James Bond series is all about ___ and secret missions.","Espionage","งานสายลับ",["Espionage","Defamation","Reasoning","Composition"]],
["The ___ cheered when the hero appeared on stage.","Audience","คนที่นั่งดูการแสดง",["Audience","Athlete","Customer","Colleague"]],
["Fresh herbs can ___ the flavor of any dish.","Enhance","ทำให้รสชาติดีขึ้น",["Enhance","Swallow","Contain","Conclude"]],
["The movie's ___ was confusing — too many characters and stories.","Plot","โครงเรื่อง",["Plot","Setting","Credit","Genre"]],
["He made the decision without ___ thought — and regretted it later.","Conscious","ทำโดยไม่ทันรู้ตัว/ไม่ได้คิด",["Conscious","Distinctive","Ambiguous","Emotional"]],
["Every band wants a ___ sound that fans recognize instantly.","Distinctive","เอกลักษณ์ที่จำได้ทันที",["Distinctive","Ordinary","Moderate","Various"]]
]},
d9:{ name:"Day 9", banner:"ไลฟ์สไตล์ กิจวัตร",
main:[
["Opinion","ความคิดเห็น (ไม่จำเป็นต้องอิงข้อเท็จจริง)","view, judgment","I always value my father's opinion."],
["Site","สถานที่ก่อสร้าง / ที่ตั้ง","location, area","Hard hats must be worn on the construction sites."],
["Hangout","ที่ที่ไปประจำ ที่แฮงเอาท์","favorite place","I drink beer at my favorite college hangout."],
["Skip","โดด ข้าม ไม่เข้า(เรียน)","miss, not attend","I wanted to skip my English lesson to visit my grandmother."],
["Regularly","เป็นประจำ สม่ำเสมอ","at regular times","It is advisable to exercise regularly."],
["Hobby","งานอดิเรก","leisure activity","Playing volleyball is one of my favorite hobbies."],
["Couch","โซฟา","sofa","I usually lie down on the couch when I'm at home."],
["Collection","ของสะสม / การสะสม","collected things","I have a lot of collections of ballad music."],
["Decide","ตัดสินใจ","make a decision","He decided to join the group."],
["Frequent (v.)","ไปบ่อยๆ ไปประจำ","visit often","I frequent the movie theaters during the summer."]
],
extra:[
["Judgment","การตัดสิน ความเห็น","opinion, decision","Opinion = a view or judgment"],
["Construction","การก่อสร้าง","building work","construction site = ไซต์ก่อสร้าง"],
["Spare time","เวลาว่าง","free time","Hangout = where one spends spare time"],
["Attend","เข้าร่วม เข้าเรียน","join, go to","Skip = fail to attend"],
["Advisable","ควรทำ แนะนำให้ทำ","recommended, wise","It is advisable to exercise regularly."],
["Leisure","เวลาว่างพักผ่อน","free time, relaxation","Hobby = done in leisure time for pleasure"],
["Interval","ช่วงเวลาห่างกัน","gap of time","Regularly = at regular intervals"],
["Furniture","เฟอร์นิเจอร์","tables, chairs, sofas","Couch is a piece of furniture"],
["Lie down","เอนตัวลงนอน","rest, recline","lie down on the couch"],
["Process","กระบวนการ ขั้นตอน","steps, method","Collection = the process of collecting"]
],
sent:[
["In my ___, the food here is overpriced.","Opinion","ความเห็นส่วนตัว",["Opinion","Habit","Duty","Choice"]],
["Workers must wear helmets at the construction ___.","Site","สถานที่ที่กำลังสร้างตึก",["Site","Couch","Hangout","Theatre"]],
["This café is our favorite ___ after class.","Hangout","ที่ที่แวะไปกันประจำ",["Hangout","Site","Collection","Routine"]],
["Don't ___ class again, or the teacher will call your parents.","Skip","ไม่ไปเรียน",["Skip","Attend","Decide","Frequent"]],
["It is advisable to back up your phone ___.","Regularly","ทำเป็นประจำสม่ำเสมอ",["Regularly","Barely","Recently","Suddenly"]],
["Collecting stamps used to be a very popular ___.","Hobby","กิจกรรมยามว่าง",["Hobby","Habit","Duty","Career"]],
["Grandma fell asleep on the ___ while watching TV.","Couch","เฟอร์นิเจอร์ในห้องนั่งเล่น",["Couch","Site","Canvas","Cabinet"]],
["His ___ of old coins is worth a lot of money.","Collection","ของที่สะสมมาทั้งหมด",["Collection","Creation","Selection","Connection"]],
["She couldn't ___ between the blue dress and the red one.","Decide","เลือกไม่ถูก",["Decide","Attend","Conclude","Skip"]],
["Tourists ___ this market every weekend for cheap clothes.","Frequent","มาบ่อยๆ เป็นประจำ",["Frequent","Skip","Maintain","Approach"]],
["Playing games all night is not ___ before an exam.","Advisable","ไม่ควรทำ",["Advisable","Regular","Frequent","Available"]],
["I read novels in my ___ time.","Leisure","ช่วงที่ว่างจากงาน",["Leisure","Collection","Opinion","Interval"]]
]},
d10:{ name:"Day 10", banner:"ศิลปะ ความคิดสร้างสรรค์",
main:[
["Abstract","นามธรรม มีอยู่ในความคิด จับต้องไม่ได้","idea, not physical","He uses abstract concepts in his paintings."],
["Expressive","แสดงความรู้สึก/ความคิดได้ดี","showing feeling","His eyes are expressive enough to show his real feeling."],
["Showcase","จัดแสดง โชว์","exhibit, display","Her album showcases her strong singing voice."],
["Culture","วัฒนธรรม (ขนบ ศิลปะ ความสำเร็จของชนชาติ)","customs, arts","The cultures in Asia are so much different from the West."],
["Creation","ผลงานสร้างสรรค์ สิ่งที่ถูกสร้างขึ้น","something made","She treats fictional creations as if they were real people."],
["Extraordinary","พิเศษเหนือธรรมดา น่าทึ่ง","remarkable, unusual","He made an extraordinary invention."],
["Canvas","ภาพวาดสีน้ำมัน / ผ้าใบวาดภาพ","oil painting","There are only few canvas painters these days."],
["Unique","มีหนึ่งเดียว ไม่เหมือนใคร","one of a kind","His drawing is unique."],
["Visual","เกี่ยวกับการมองเห็น","seen by the eye","I was impressed by the dramatic visual effect."],
["Masterpiece","ผลงานชิ้นเอก","great work","His masterpiece is unique compared to other students."]
],
extra:[
["Concept","แนวคิด","idea","abstract concepts = แนวคิดนามธรรม"],
["Convey","สื่อ ถ่ายทอด (ความรู้สึก/ความหมาย)","communicate","Expressive = conveying thought or feeling"],
["Exhibit","จัดแสดง","display, show","Showcase = to exhibit or display"],
["Customs","ขนบธรรมเนียม ประเพณี","traditions","Culture = the customs, arts... of a nation"],
["Achievement","ความสำเร็จ","success","...and achievements of a social group"],
["Invention","สิ่งประดิษฐ์","new creation","He made an extraordinary invention."],
["Remarkable","น่าทึ่ง โดดเด่น","amazing, notable","Extraordinary = very unusual or remarkable"],
["Artistry","ฝีมือทางศิลปะ","artistic skill","Masterpiece = outstanding artistry"],
["Fictional","ที่แต่งขึ้น ไม่มีอยู่จริง","made-up, imaginary","fictional creations = ตัวละครที่แต่งขึ้น"],
["Workmanship","ฝีมือช่าง ความประณีต","craft quality","outstanding workmanship"]
],
sent:[
["Love and freedom are ___ ideas — you cannot touch them.","Abstract","จับต้องไม่ได้",["Abstract","Concrete","Visual","Unique"]],
["Her face is so ___ that you always know how she feels.","Expressive","อ่านความรู้สึกได้จากหน้า",["Expressive","Attractive","Impressive","Aggressive"]],
["The gallery will ___ young Thai artists next month.","Showcase","นำผลงานมาแสดง",["Showcase","Purchase","Conclude","Compose"]],
["Respecting elders is an important part of Thai ___.","Culture","ขนบและวิถีของคนไทย",["Culture","History","Religion","Language"]],
["The artist's latest ___ is made entirely of recycled plastic.","Creation","ผลงานที่สร้างขึ้น",["Creation","Collection","Correction","Connection"]],
["She has an ___ memory — she remembers every phone number.","Extraordinary","เหนือกว่าคนทั่วไปมาก",["Extraordinary","Ordinary","Necessary","Temporary"]],
["The old ___ hanging in the museum is worth millions.","Canvas","ภาพวาดสีน้ำมัน",["Canvas","Couch","Curtain","Cabinet"]],
["Every fingerprint is ___ — no two people share the same one.","Unique","ไม่มีอันไหนซ้ำกันเลย",["Unique","Similar","Typical","Regular"]],
["The concert was amazing, with dramatic ___ effects on the big screen.","Visual","เกี่ยวกับสิ่งที่ตามองเห็น",["Visual","Verbal","Vocal","Virtual"]],
["The Mona Lisa is Leonardo's most famous ___.","Masterpiece","ผลงานที่ดีที่สุด",["Masterpiece","Creation","Canvas","Collection"]],
["A picture can ___ feelings that words cannot.","Convey","สื่อความรู้สึกออกมา",["Convey","Contain","Conclude","Conquer"]],
["Winning the gold medal was her greatest ___.","Achievement","ความสำเร็จสูงสุด",["Achievement","Agreement","Arrangement","Announcement"]]
]},
d11:{ name:"Day 11", banner:"อารมณ์ สังคม ปฏิสัมพันธ์",
main:[
["Apologize","ขอโทษ กล่าวคำขอโทษ","say sorry","He apologized for accusing her falsely."],
["Annoy","ทำให้รำคาญ กวนใจ","irritate, bother","He's just trying to annoy you."],
["React","ตอบสนอง แสดงปฏิกิริยา","respond","He reacted angrily to the news of his dismissal."],
["Occasion","โอกาส วาระพิเศษ งานสำคัญ","special event","She was presented with a gold watch to mark the occasion."],
["Mingle","เดินทักทายเข้าสังคม พูดคุยปะปน","socialize, mix","I had the chance to mingle with the other team."],
["Unexpected","ไม่คาดคิด เหนือความคาดหมาย","surprising, unforeseen","That exchange of insults was unexpected."],
["Outcast","คนนอกคอก คนที่ถูกสังคมกีดกัน","rejected person","He felt like an outcast watching his friends."],
["Affair","เรื่องราว เหตุการณ์","event, matter","This affair boosts my confidence in the group."],
["Absorb","ซึมซับ รับเข้าไป (ข้อมูล/ความรู้)","take in","She absorbed the information in silence."],
["Refuse","ปฏิเสธ ไม่ยอม","decline, reject","The teacher refused the student's invitation."]
],
extra:[
["Excuse","ข้อแก้ตัว เหตุผลแก้ตัว","reason, justification","apologize = offer an apology or excuse"],
["Insult","คำดูถูก การสบประมาท","offensive remark","some fault, insult, or injury"],
["Injury","การบาดเจ็บ ความเสียหาย","harm, damage","fault, insult, failure, or injury"],
["Irritation","ความรำคาญ การระคายเคือง","annoyance","Annoy = cause irritation"],
["Particular","เฉพาะเจาะจง โดยเฉพาะ","specific","respond in a particular way"],
["Noteworthy","น่าสังเกต น่าจดจำ","remarkable","a special or noteworthy event"],
["Assimilate","ซึมซับกลืนเป็นของตน ทำความเข้าใจ","absorb, take in","Absorb = take in and assimilate"]
],
sent:[
["He ___ to her for shouting during the meeting.","Apologized","ขอโทษที่ทำผิด",["Apologized","Reacted","Refused","Absorbed"]],
["Please stop that noise — you ___ everyone in the room.","Annoy","ทำให้คนอื่นรำคาญ",["Annoy","Entertain","Mingle","Absorb"]],
["How did she ___ when she heard the surprising news?","React","แสดงปฏิกิริยาตอบ",["React","Refuse","Apologize","Wander"]],
["A wedding is a joyful ___ for the whole family.","Occasion","งาน/วาระพิเศษ",["Occasion","Outcast","Affair","Injury"]],
["At the party, guests began to ___ and make new friends.","Mingle","เดินทักทายเข้าสังคม",["Mingle","Refuse","Annoy","React"]],
["The ending of the movie was completely ___.","Unexpected","ไม่มีใครคาดคิด",["Unexpected","Ordinary","Definite","Punctual"]],
["Feeling like an ___, he ate lunch alone every day.","Outcast","คนที่ถูกกีดกันจากกลุ่ม",["Outcast","Idol","Colleague","Guest"]],
["The whole ___ was reported in the newspapers.","Affair","เรื่องราว/เหตุการณ์",["Affair","Occasion","Region","Forecast"]],
["Good students ___ new information quickly.","Absorb","ซึมซับความรู้",["Absorb","Refuse","Annoy","Waste"]],
["She politely ___ to sign the unfair contract.","Refused","ไม่ยอมทำ",["Refused","Reacted","Mingled","Absorbed"]]
]},
d12:{ name:"Day 12", banner:"ฤดูร้อน ทะเล วันหยุด",
main:[
["Sunscreen","ครีมกันแดด","sunblock","SPF 15 sunscreen theoretically prevents reddening longer."],
["Sandcastle","ปราสาททราย","sand model","I used to build sandcastles when I was a kid."],
["Temperature","อุณหภูมิ","degree of heat/cold","The food must be kept at a low temperature."],
["Tropical","เขตร้อน แบบเมืองร้อน","hot-climate","He was unused to the tropical climate."],
["Sunburn","ผิวไหม้แดด","sun-damaged skin","I'm trying not to get sunburn."],
["Desire","ความปรารถนา ความอยาก","strong wish","She had a lifelong desire to visit China."],
["Vacation","วันหยุดพักผ่อน การไปเที่ยว","holiday","Tom is on vacation in Australia."],
["Entertain","ต้อนรับเลี้ยงดูแขก / ให้ความบันเทิง","host, amuse","She has a dining room to entertain her friends."],
["Wander","เดินเตร่ ท่องไปเรื่อย","roam","I wandered aimlessly around the garden."],
["Dive","กระโดดหัวปักลงน้ำ ดำน้ำ","plunge","My friend dives in the sea every time."]
],
extra:[
["Theoretically","ตามทฤษฎี ในทางทฤษฎี","in theory","will theoretically prevent reddening"],
["Reddening","การกลายเป็นสีแดง (ผิวแดง)","turning red","prevent reddening of the skin"],
["Overexposure","การโดน(แดด)มากเกินไป","too much exposure","overexposure to ultraviolet rays"],
["Blistering","การเกิดตุ่มพอง","forming blisters","blistering and peeling of the skin"],
["Peeling","การลอก (ผิวลอก)","coming off in layers","blistering and peeling"],
["Inflammation","การอักเสบ บวมแดง","swelling, soreness","reddening, inflammation of the skin"],
["Definite","แน่นอน ชัดเจน","clear, fixed","without a definite destination"],
["Aimlessly","อย่างไร้จุดหมาย","without purpose","wandered aimlessly around"]
],
sent:[
["Put on ___ before you go to the beach.","Sunscreen","ครีมกันแดด",["Sunscreen","Sunburn","Perfume","Shampoo"]],
["The kids built a ___ near the water.","Sandcastle","ปราสาททราย",["Sandcastle","Snowball","Fireplace","Scarf"]],
["Keep the medicine at a low ___.","Temperature","ความร้อน-เย็น",["Temperature","Pressure","Distance","Volume"]],
["Thailand has a hot, ___ climate.","Tropical","แบบเมืองร้อน",["Tropical","Polar","Elevated","Stagnant"]],
["Too much sun can give you a painful ___.","Sunburn","ผิวไหม้แดด",["Sunburn","Sunscreen","Bandage","Allergy"]],
["She had a strong ___ to become a doctor.","Desire","ความปรารถนาอย่างแรง",["Desire","Refusal","Burden","Doubt"]],
["We are going on a two-week ___ to Japan.","Vacation","ทริปพักผ่อน",["Vacation","Occasion","Region","Affair"]],
["They love to ___ friends with a big dinner.","Entertain","ต้อนรับเลี้ยงดู",["Entertain","Annoy","Refuse","Wander"]],
["He likes to ___ around the old town with no plan.","Wander","เดินเตร่ไปเรื่อย",["Wander","Dive","React","Mingle"]],
["Be careful when you ___ into the shallow pool.","Dive","กระโดดลงน้ำ",["Dive","Wander","Float","Climb"]]
]},
d13:{ name:"Day 13", banner:"ฤดูหนาว หิมะ ภูมิศาสตร์",
main:[
["Forecast","การพยากรณ์ คำทำนาย (อากาศ/แนวโน้ม)","prediction","The newscaster reported a gloomy forecast today."],
["Region","ภูมิภาค เขตพื้นที่","area, zone","Some regions in Australia are cold, others temperate."],
["Fireplace","เตาผิง","hearth","They sat by the fireplace and talked."],
["Avalanche","หิมะถล่ม","snowslide","Four people died when an avalanche buried them."],
["Snowball","ก้อนหิมะ (ปั้นขว้าง)","packed snow ball","I throw snowballs at my friends."],
["Elevated","ยกสูงขึ้น อยู่สูง","raised","Temperature at elevated areas is normally cooler."],
["Sled","เลื่อนหิมะ","snow vehicle","I have never ridden a sled."],
["Twigs","กิ่งไม้เล็กๆ","small branches","Birds make their nests on leafy twigs."],
["Scarf","ผ้าพันคอ","neck cloth","My grandmother likes to wear a scarf."],
["Snowboard","กระดานเล่นหิมะ","snow board","Josh received a snowboard on his birthday."]
],
extra:[
["Prediction","คำทำนาย การคาดการณ์","forecast, guess","Forecast = a prediction of future events"],
["Chimney","ปล่องไฟ","smoke pipe","a hearth at the base of a chimney"],
["Rapidly","อย่างรวดเร็ว","quickly, fast","falling rapidly down a mountainside"],
["Conveying","การขนส่ง ลำเลียง","carrying","for conveying goods or passengers"],
["Slender","เรียว บาง","slim, thin","a slender woody shoot"],
["Branch","กิ่งก้าน (ของต้นไม้)","tree limb","growing from a branch or stem"],
["Shrub","ไม้พุ่ม","bush","a shoot of a tree or shrub"],
["Resembling","คล้ายกับ ดูเหมือน","looking like","a board resembling a short, broad ski"]
],
sent:[
["The weather ___ says it will snow tomorrow.","Forecast","พยากรณ์อากาศ",["Forecast","Region","Occasion","Avalanche"]],
["The northern ___ of the country is very cold.","Region","เขตพื้นที่",["Region","Fireplace","Scarf","Forecast"]],
["They warmed their hands by the ___.","Fireplace","เตาผิง",["Fireplace","Avalanche","Snowboard","Chimney"]],
["An ___ suddenly buried the mountain village in snow.","Avalanche","หิมะถล่ม",["Avalanche","Occasion","Region","Sunburn"]],
["The children threw a ___ at each other.","Snowball","ก้อนหิมะ",["Snowball","Sandcastle","Scarf","Twig"]],
["It is colder in the ___ areas of the mountain.","Elevated","พื้นที่ยกสูง",["Elevated","Tropical","Lowered","Crowded"]],
["In winter, dogs pulled the ___ across the snow.","Sled","เลื่อนหิมะ",["Sled","Snowboard","Boat","Bicycle"]],
["The bird built its nest from small ___.","Twigs","กิ่งไม้เล็กๆ",["Twigs","Scarves","Snowballs","Bricks"]],
["She wrapped a warm ___ around her neck.","Scarf","ผ้าพันคอ",["Scarf","Sled","Twig","Snowball"]],
["He learned to ride a ___ down the snowy hill.","Snowboard","กระดานเล่นหิมะ",["Snowboard","Sled","Sandcastle","Fireplace"]]
]}
};

const BIEBER = [
["Sorry","ขอโทษ เสียใจ","apologize","Sorry"],
["Forgive","ให้อภัย","pardon","Sorry"],
["Purpose","จุดมุ่งหมาย เป้าหมายชีวิต","goal, intention","Purpose"],
["Lonely","เหงา โดดเดี่ยว","alone, sad","Lonely"],
["Ghost","ผี / ความทรงจำถึงคนที่จากไป","spirit, memory","Ghost"],
["Confident","มั่นใจในตัวเอง","sure of yourself","Confident"],
["Intentions","ความตั้งใจ (ดีๆ)","plans, aims","Intentions"],
["Holy","ศักดิ์สิทธิ์","sacred","Holy"],
["Company","การอยู่เป็นเพื่อนกัน","being together","Company"],
["Mean","หมายความว่า","signify","What Do You Mean?"],
["Stay","อยู่ต่อ ไม่ไปไหน","remain","Stay"],
["Anyone","ใครสักคน","any person","Anyone"],
["Peaches","ลูกพีช","a sweet fruit","Peaches"],
["Baby","ที่รัก / เด็กทารก","darling; infant","Baby"],
["Never","ไม่มีวัน ไม่เคยเลย","not ever","Never Say Never"],
["Beauty","ความงาม","prettiness","Beauty and a Beat"],
["Mistletoe","ต้นมิสเซิลโท (ของคริสต์มาส)","Christmas plant","Mistletoe"],
["Believe","เชื่อ ศรัทธา","trust","อัลบั้ม Believe"]
];

// ============================================================
// FORMAL — คำพูดเล่นๆ ในชีวิตประจำวัน -> คำทางการที่ใช้ตอนเขียนเมล/รายงาน
// [casual, formal, ความหมายไทย, ตัวอย่างประโยคทางการ]
// ============================================================
const FORMAL = [
["so","therefore / thus","ดังนั้น","The results were inconclusive; therefore, further testing is required."],
["but","however","แต่ / อย่างไรก็ตาม","The plan is sound; however, the budget remains a concern."],
["also","moreover / furthermore","อีกทั้ง / ยิ่งไปกว่านั้น","The design is elegant; moreover, it is cost-effective."],
["get","obtain / receive","ได้รับ","Please ensure you obtain approval before proceeding."],
["buy","purchase","ซื้อ","The company will purchase new equipment next quarter."],
["help","assist","ช่วยเหลือ","Our team is available to assist you with the transition."],
["need","require","ต้องการ / จำเป็นต้อง","This position requires three years of experience."],
["use","utilize / employ","ใช้","We utilize advanced tools to ensure accuracy."],
["show","demonstrate / indicate","แสดง / บ่งชี้","The figures demonstrate a clear upward trend."],
["tell","inform / notify","แจ้ง / บอกให้ทราบ","Please inform us of any changes in advance."],
["ask","request / inquire","ขอ / สอบถาม","We kindly request your response by Friday."],
["start","commence","เริ่ม","The meeting will commence at 9 a.m. sharp."],
["end","conclude","จบ / สรุป","The report concludes with several recommendations."],
["find out","ascertain / discover","หาข้อมูล / ตรวจสอบให้แน่ใจ","We must ascertain the cause before taking action."],
["fix","resolve","แก้ไข","We are working to resolve the issue promptly."],
["give","provide","ให้ / จัดหา","The vendor will provide full documentation."],
["want","wish","ต้องการ / ปรารถนา","We wish to express our gratitude for your support."],
["a lot of","numerous / a great deal of","จำนวนมาก","The proposal received numerous positive responses."],
["enough","sufficient","เพียงพอ","Please ensure sufficient funds are available."],
["about (number)","approximately","ประมาณ (จำนวน)","The project will take approximately six weeks."],
["about (topic)","regarding / concerning","เกี่ยวกับ (เรื่อง)","I am writing regarding your recent inquiry."],
["because","due to / as","เพราะว่า / เนื่องจาก","The event was postponed due to bad weather."],
["before","prior to","ก่อน","Please review the terms prior to signing."],
["after","following","หลังจาก","Following the meeting, minutes will be circulated."],
["happen","occur","เกิดขึ้น","Should any problems occur, please contact support."],
["try","attempt","พยายาม","We will attempt to accommodate your request."],
["next","subsequent","ถัดไป / ที่ตามมา","Details will be shared in a subsequent email."],
["now","currently / at present","ตอนนี้ / ในปัจจุบัน","The system is currently undergoing maintenance."],
["soon","shortly","เร็วๆ นี้","We will respond to your message shortly."],
["big","significant / substantial","ใหญ่ / สำคัญมาก","The change had a significant impact on sales."],
["maybe","perhaps / possibly","บางที / อาจจะ","Perhaps a follow-up meeting would be beneficial."],
["say","state","พูด / ระบุ","As stated in the contract, payment is due monthly."],
["let","allow / permit","อนุญาต / ทำให้","This upgrade will allow faster processing."],
["keep","retain / maintain","เก็บ / รักษาไว้","Please retain a copy for your records."],
["make sure","ensure","ทำให้แน่ใจ","Please ensure all fields are completed."],
["put off","postpone","เลื่อนออกไป","The launch has been postponed until further notice."],
["go up","increase","เพิ่มขึ้น","Prices are expected to increase next year."],
["go down","decrease / decline","ลดลง","Sales declined slightly in the third quarter."],
["cheap","affordable / inexpensive","ราคาถูก","We offer affordable solutions for small businesses."],
["job","position","งาน / ตำแหน่ง","She was offered a senior position at the firm."],
["boss","supervisor / superior","เจ้านาย / หัวหน้า","Please forward the request to your supervisor."],
["in short","in summary / to conclude","กล่าวโดยสรุป","In summary, the strategy proved highly effective."],
["sorry","apologize / regret","ขอโทษ / เสียใจ","We regret to inform you of the delay."],
["really","considerably / genuinely","อย่างมาก","Efficiency improved considerably after the update."],
["free","complimentary","ฟรี / ไม่มีค่าใช้จ่าย","Members receive complimentary access to all events."]
];

const DICT = {
"a":"หนึ่ง (คำนำหน้านาม)","an":"หนึ่ง (คำนำหน้านาม)","the":"(คำนำหน้านามชี้เฉพาะ)",
"she":"เธอ (ผู้หญิง)","he":"เขา (ผู้ชาย)","it":"มัน","i":"ฉัน","we":"พวกเรา","you":"คุณ","they":"พวกเขา",
"her":"ของเธอ / เธอ","his":"ของเขา","my":"ของฉัน","your":"ของคุณ","their":"ของพวกเขา","our":"ของพวกเรา","its":"ของมัน","him":"เขา","them":"พวกเขา","me":"ฉัน","us":"พวกเรา",
"is":"คือ / เป็น","are":"คือ / เป็น (พหูพจน์)","was":"เคยเป็น (อดีต)","were":"เคยเป็น (อดีต พหูพจน์)","be":"เป็น อยู่ คือ","been":"เป็น (ช่อง 3)","am":"เป็น (กับ I)",
"do":"ทำ","does":"ทำ","did":"ทำ (อดีต)","done":"ทำ (ช่อง 3)","don't":"ไม่","doesn't":"ไม่","didn't":"ไม่ (อดีต)",
"can":"สามารถ","cannot":"ไม่สามารถ","can't":"ไม่สามารถ","could":"สามารถ (อดีต)","couldn't":"ไม่สามารถ (อดีต)","will":"จะ","would":"จะ (สุภาพ/สมมติ)","must":"ต้อง","should":"ควร",
"and":"และ","or":"หรือ","but":"แต่","so":"ดังนั้น / มากจน","because":"เพราะว่า","if":"ถ้า","that":"ว่า / นั้น","this":"นี้","these":"เหล่านี้","those":"เหล่านั้น","which":"ซึ่ง","who":"ผู้ซึ่ง / ใคร","when":"เมื่อ","while":"ในขณะที่","until":"จนกระทั่ง",
"in":"ใน","on":"บน","at":"ที่","to":"ไปยัง / เพื่อ","of":"ของ","with":"กับ / ด้วย","for":"สำหรับ / เพื่อ","from":"จาก","by":"โดย / ข้างๆ","about":"เกี่ยวกับ","into":"เข้าไปใน","between":"ระหว่าง","during":"ในระหว่าง","after":"หลังจาก","before":"ก่อน","without":"โดยปราศจาก","among":"ท่ามกลาง","near":"ใกล้",
"not":"ไม่","no":"ไม่","never":"ไม่เคย","always":"เสมอ","again":"อีกครั้ง","too":"เกินไป / ด้วย","very":"มาก","more":"มากกว่า","most":"ที่สุด","many":"หลาย / มาก","much":"มาก","any":"ใดๆ","some":"บาง","all":"ทั้งหมด","every":"ทุกๆ","each":"แต่ละ","only":"เท่านั้น","also":"ด้วย","both":"ทั้งสอง","enough":"เพียงพอ","few":"น้อย","little":"เล็ก / น้อย","other":"อื่นๆ","another":"อีกอันหนึ่ง","same":"เหมือนเดิม","such":"เช่นนั้น",
"drinks":"ดื่ม","coffee":"กาแฟ","morning":"ตอนเช้า","work":"งาน / ทำงาน","daily":"ประจำวัน","boy":"เด็กผู้ชาย","fell":"ล้ม / ตก (อดีตของ fall)","down":"ลง","nurse":"พยาบาล","put":"วาง / ติด","knee":"หัวเข่า","full":"เต็ม / อิ่ม","eat":"กิน","cake":"เค้ก","plays":"เล่น","three":"สาม","piano":"เปียโน","guitar":"กีตาร์","drums":"กลอง","musical":"ทางดนตรี","soup":"ซุป","brother":"พี่ชาย / น้องชาย","mother":"แม่","bear":"หมี","watched":"เฝ้าดู (อดีต)","playing":"กำลังเล่น","snow":"หิมะ","new":"ใหม่","song":"เพลง","phone":"โทรศัพท์","listen":"ฟัง","offline":"แบบไม่ใช้เน็ต","sit":"นั่ง","next":"ถัดไป / ข้างๆ","office":"ออฟฟิศ / ที่ทำงาน","large":"ใหญ่","countries":"ประเทศ (พหูพจน์)","country":"ประเทศ","reading":"การอ่าน","comic":"การ์ตูน","books":"หนังสือ","book":"หนังสือ / จอง","favorite":"ที่ชอบที่สุด","weekends":"สุดสัปดาห์","weekend":"สุดสัปดาห์",
"train":"รถไฟ","people":"ผู้คน","pushing":"เบียด / ดัน","get":"ได้ / ไปถึง","everyone":"ทุกคน","trusts":"ไว้ใจ","meetings":"การประชุม","meeting":"การประชุม","check":"ตรวจสอบ","think":"คิด","visit":"ไปเยี่ยม / ไปเที่ยว","temple":"วัด","lunch":"อาหารเที่ยง","regular":"สม่ำเสมอ / ปกติ","exercise":"ออกกำลังกาย","energy":"พลังงาน","day":"วัน","police":"ตำรวจ","arrest":"จับกุม","there":"ที่นั่น / มี","aunt":"ป้า / น้าสาว","passed":"ผ่าน / เสีย(ชีวิต)","away":"จากไป","old":"เก่า / แก่","house":"บ้าน","river":"แม่น้ำ","kinds":"ชนิด","public":"สาธารณะ","buses":"รถเมล์","boats":"เรือ","trains":"รถไฟ","stop":"หยุด","sister":"พี่สาว / น้องสาว","haircut":"ทรงผม","getting":"กำลังเริ่ม","upset":"เสียใจ / หงุดหงิด","brown":"สีน้ำตาล","rice":"ข้าว","white":"สีขาว","than":"กว่า","planning":"กำลังวางแผน","family":"ครอบครัว","haven't":"ยังไม่ได้","met":"พบ (อดีตของ meet)","five":"ห้า","years":"ปี",
"despite":"ทั้งๆ ที่","argument":"การโต้เถียง ทะเลาะ","companies":"บริษัท (พหูพจน์)","company":"บริษัท / การอยู่เป็นเพื่อน","want":"ต้องการ","business":"ธุรกิจ","relationship":"ความสัมพันธ์","politician":"นักการเมือง","gave":"ให้ (อดีตของ give)","answer":"คำตอบ","reporters":"นักข่าว","kept":"ยังคง (อดีตของ keep)","asking":"ถาม","question":"คำถาม","operation":"การผ่าตัด","grandpa":"คุณปู่ / คุณตา","walk":"เดิน","help":"ช่วยเหลือ","actress":"นักแสดงหญิง","decided":"ตัดสินใจ (อดีต)","magazine":"นิตยสาร","printing":"การตีพิมพ์","false":"เท็จ ไม่จริง","stories":"เรื่องราว","story":"เรื่อง","took":"ใช้เวลา (อดีตของ take)","fear":"ความกลัว","speaking":"การพูด","film":"ภาพยนตร์","won":"ชนะ / ได้รับ (อดีตของ win)","award":"รางวัล","stunning":"สวยงามตะลึง","recognize":"จำได้","paintings":"ภาพวาด","painting":"ภาพวาด","immediately":"ทันที","style":"สไตล์ ลีลา","good":"ดี","comedy":"ตลก","needs":"ต้องการ","perfect":"สมบูรณ์แบบ","timing":"จังหวะเวลา","sharp":"เฉียบคม","director":"ผู้กำกับ","changed":"เปลี่ยน (อดีต)","play":"ละครเวที / เล่น","small":"เล็ก","savings":"เงินออม","grow":"เติบโต","amount":"จำนวน",
"even":"แม้แต่","losing":"การสูญเสีย","everything":"ทุกสิ่ง","man":"ผู้ชาย","lost":"สูญเสีย (อดีต)","novel":"นิยาย","life":"ชีวิต","rural":"ชนบท","honesty":"ความซื่อสัตย์","warmth":"ความอบอุ่น","critics":"นักวิจารณ์","praised":"ชื่นชม (อดีต)","complex":"ซับซ้อน","unexpected":"คาดไม่ถึง","twists":"จุดหักมุม","cold":"เย็น / หนาว","war":"สงคราม","sides":"ฝ่าย","used":"ใช้ (อดีต)","steal":"ขโมย","military":"ทางทหาร","secrets":"ความลับ","secret":"ความลับ","soundtrack":"เพลงประกอบ","greatly":"อย่างมาก","emotional":"ทางอารมณ์ ซาบซึ้ง","impact":"ผลกระทบ","scene":"ฉาก (ในหนัง)","manners":"มารยาท","guest":"แขก","felt":"รู้สึก (อดีตของ feel)","perfectly":"อย่างสมบูรณ์","welcomed":"ได้รับการต้อนรับ","fingerprints":"ลายนิ้วมือ","fingerprint":"ลายนิ้วมือ","glass":"แก้ว","detective":"นักสืบ","thief":"ขโมย (คน)","left-handed":"ถนัดมือซ้าย","moving":"การย้าย","out":"ออก","eighteen":"สิบแปด","taught":"สอน (อดีตของ teach)","financially":"ทางการเงิน","consider":"ถือว่า / มองว่า","architecture":"สถาปัตยกรรม","reply":"ตอบกลับ","angry":"โกรธ","email":"อีเมล","forgot":"ลืม (อดีตของ forget)","attachment":"ไฟล์แนบ",
"town":"เมืองเล็กๆ","romans":"ชาวโรมัน","europe":"ทวีปยุโรป","two":"สอง","thousand":"พัน","ago":"ที่แล้ว","muddy":"เปื้อนโคลน","footprints":"รอยเท้า","someone":"ใครบางคน","entered":"เข้าไป (อดีต)","romance":"แนวรัก โรแมนติก","popular":"เป็นที่นิยม","teenagers":"วัยรุ่น","magician's":"ของนักมายากล","magician":"นักมายากล","show":"การแสดง","smoke":"ควัน","lighting":"แสงไฟ","classic":"คลาสสิก","films":"ภาพยนตร์","sunday":"วันอาทิตย์","first":"แรก","manager":"ผู้จัดการ","strict":"เข้มงวด","keeps":"ทำให้...ตลอด","guessing":"เดา","last":"สุดท้าย","page":"หน้า (หนังสือ)","beginning":"ตอนต้น","lists":"แสดงรายชื่อ","actors":"นักแสดง","james":"เจมส์ (ชื่อคน)","bond":"บอนด์ (ชื่อคน)","series":"ซีรีส์ / ชุด","missions":"ภารกิจ","cheered":"ส่งเสียงเชียร์","hero":"พระเอก / ฮีโร่","appeared":"ปรากฏตัว","stage":"เวที","fresh":"สด","herbs":"สมุนไพร","flavor":"รสชาติ","dish":"จานอาหาร","confusing":"น่าสับสน","characters":"ตัวละคร","decision":"การตัดสินใจ","regretted":"เสียใจภายหลัง","later":"ภายหลัง","band":"วงดนตรี","sound":"เสียง","fans":"แฟนคลับ","instantly":"ในทันที",
"food":"อาหาร","here":"ที่นี่","overpriced":"แพงเกินจริง","workers":"คนงาน","wear":"สวมใส่","helmets":"หมวกนิรภัย","construction":"การก่อสร้าง","café":"คาเฟ่","class":"คาบเรียน / ชั้นเรียน","teacher":"ครู","call":"โทรหา / เรียก","parents":"พ่อแม่","advisable":"ควรทำ","back":"กลับ / สำรอง","up":"ขึ้น","collecting":"การสะสม","stamps":"แสตมป์","grandma":"คุณย่า / คุณยาย","asleep":"หลับ","watching":"กำลังดู","tv":"ทีวี","coins":"เหรียญ","worth":"มีมูลค่า","lot":"มาก","money":"เงิน","blue":"สีน้ำเงิน / ฟ้า","dress":"ชุดเดรส","red":"สีแดง","one":"หนึ่ง / อันหนึ่ง","tourists":"นักท่องเที่ยว","market":"ตลาด","cheap":"ราคาถูก","clothes":"เสื้อผ้า","games":"เกม","night":"กลางคืน","exam":"การสอบ","novels":"นิยาย","time":"เวลา",
"love":"ความรัก","freedom":"อิสรภาพ","ideas":"ความคิด","touch":"สัมผัส","face":"ใบหน้า","know":"รู้","how":"อย่างไร","feels":"รู้สึก","gallery":"หอศิลป์","young":"หนุ่มสาว / รุ่นใหม่","thai":"ไทย","artists":"ศิลปิน","artist's":"ของศิลปิน","month":"เดือน","respecting":"การเคารพ","elders":"ผู้อาวุโส","important":"สำคัญ","part":"ส่วน","latest":"ล่าสุด","made":"ทำ / สร้าง (อดีต)","entirely":"ทั้งหมด","recycled":"รีไซเคิล","plastic":"พลาสติก","memory":"ความจำ","remembers":"จำได้","number":"หมายเลข","hanging":"แขวนอยู่","museum":"พิพิธภัณฑ์","millions":"หลายล้าน","share":"แบ่งปัน / มีร่วมกัน","concert":"คอนเสิร์ต","amazing":"น่าทึ่ง","dramatic":"น่าตื่นตา","big":"ใหญ่","screen":"จอ","picture":"รูปภาพ","feelings":"ความรู้สึก","words":"คำพูด","winning":"การชนะ","gold":"ทอง","medal":"เหรียญรางวัล","greatest":"ยิ่งใหญ่ที่สุด",
"buy":"ซื้อ","rent":"เช่า","cheaper":"ถูกกว่า","house.":"บ้าน","home":"บ้าน","watch":"ดู","movies":"หนัง","children":"เด็กๆ","valuable":"มีค่า","because":"เพราะ","says":"พูดว่า","wanted":"ต้องการ (อดีต)","lesson":"บทเรียน","grandmother":"คุณย่า / คุณยาย","volleyball":"วอลเลย์บอล","usually":"โดยปกติ","lie":"นอนเอน / โกหก","ballad":"เพลงช้า (บัลลาด)","music":"ดนตรี เพลง","join":"เข้าร่วม","group":"กลุ่ม","theaters":"โรงหนัง","summer":"ฤดูร้อน","hats":"หมวก","hard":"แข็ง / ยาก","worn":"สวมใส่ (ช่อง 3)","beer":"เบียร์","college":"วิทยาลัย","value":"ให้คุณค่า","father's":"ของพ่อ",
"suspect":"สงสัย / ผู้ต้องสงสัย","stole":"ขโมย (อดีตของ steal)","proof":"หลักฐาน","yet":"ยัง","recurring":"เกิดขึ้นซ้ำๆ","dream":"ความฝัน","flying":"บิน","ocean":"มหาสมุทร","weather":"สภาพอากาศ","clear":"แจ่มใส / ชัดเจน","sky":"ท้องฟ้า","aspects":"แง่มุม ด้านต่างๆ","problem":"ปัญหา","deciding":"การตัดสินใจ","capable":"มีความสามารถ","leader":"ผู้นำ","handle":"รับมือ จัดการ","crisis":"วิกฤต","rainy":"ฝนตก","burden":"ภาระ","lent":"ให้ยืม (อดีตของ lend)","career":"อาชีพการงาน","medicine":"การแพทย์ / ยา","express":"แสดงออก","child":"เด็ก","hospital":"โรงพยาบาล","marathon":"การวิ่งมาราธอน","homework":"การบ้าน","government":"รัฐบาล","road":"ถนน","traffic":"การจราจร","reduce":"ลด","anger":"ความโกรธ","insomnia":"โรคนอนไม่หลับ","awake":"ตื่น","boxer":"นักมวย","punch":"หมัด / ต่อย","powerful":"ทรงพลัง","password":"รหัสผ่าน","account":"บัญชี","hackers":"แฮกเกอร์","sales":"ยอดขาย","growth":"การเติบโต","tide":"กระแสน้ำขึ้นลง","sandcastles":"ปราสาททราย","ancient":"โบราณ","national":"แห่งชาติ","deleted":"ที่ถูกลบ","files":"ไฟล์","dog":"สุนัข","trained":"ฝึก (อดีต)","ball":"ลูกบอล","bring":"นำมา","brave":"กล้าหาญ","cruel":"โหดร้าย","boss":"เจ้านาย","unfair":"ไม่ยุติธรรม","orders":"คำสั่ง","funds":"เงินทุน","spent":"ใช้จ่าย (อดีต)","personal":"ส่วนตัว","luxuries":"ของฟุ่มเฟือย","patient":"ผู้ป่วย / อดทน","difficult":"ยาก","saved":"ประหยัด / ช่วยไว้ (อดีต)","believed":"เชื่อ (อดีต)","smoking":"การสูบบุหรี่","allowed":"อนุญาต","parties":"งานปาร์ตี้","pleasure":"ความสุขสำราญ","responsibility":"ความรับผิดชอบ","fat":"ไขมัน / อ้วน","doctor":"หมอ","appetite":"ความอยากอาหาร","lose":"สูญเสีย / ลด","weight":"น้ำหนัก","worried":"กังวล","test":"การทดสอบ","prepared":"เตรียมตัว (อดีต)","farming":"การทำเกษตร","survived":"เอาชีวิตรอด (อดีต)","hunting":"การล่าสัตว์","animals":"สัตว์","picking":"เก็บ / เด็ด","wild":"ป่า / ตามธรรมชาติ","plants":"พืช","illegal":"ผิดกฎหมาย","ethical":"ทางจริยธรรม","debate":"การถกเถียง","skydiving":"การกระโดดร่ม","sign":"เซ็นชื่อ / ป้าย","release":"ปลดปล่อย / ยกเว้น","blame":"ความผิด / โทษ","results":"ผลลัพธ์","waiting":"การรอคอย","weeks":"สัปดาห์","coin":"เหรียญ","vowel":"สระ","sounds":"เสียง","gliding":"ร่อน / เลื่อนไหล","together":"ด้วยกัน","reasons":"เหตุผล","precious":"ล้ำค่า","natural":"ทางธรรมชาติ","destroyed":"ทำลาย (อดีต)","homes":"บ้าน","team":"ทีม","rivals":"คู่แข่ง","skin":"ผิวหนัง","sweater":"เสื้อกันหนาว","wool":"ขนสัตว์ / ผ้าวูล","peanuts":"ถั่วลิสง","twins":"ฝาแฝด","broke":"แตกหัก (อดีตของ break)","runners":"นักวิ่ง","quiet":"เงียบ","water":"น้ำ"
};


// ============================================================
// IELTS — 500 คำศัพท์ IELTS จาก chulatutor.com (กันซ้ำกับ VOCAB แล้ว)
// [word, "(pos) คำแปลไทย", ตัวอย่างประโยค]
// เพิ่มทีละก้อน — ก้อนที่ 1/5
// ============================================================
const IELTS = [
["Architecture","(n) สถาปัตยกรรม","There are examples of most styles of architecture in the town."],
["Abandon","(v) ละทิ้ง","People often simply abandon their pets when they go abroad."],
["Accommodation","(n) ที่พัก","We may have to provide alternative accommodation for you."],
["Accommodate","(v) จัดที่อยู่ให้","The hotel can accommodate up to 500 guests."],
["Addictive","(adj) เสพติด","The game is very addictive."],
["Abide by","(phrv) ยอมปฏิบัติตาม","You'll have to abide by the rules of the club."],
["Automobile","(n) รถยนต์","Learning to drive an automobile is not easy."],
["Architect","(n) ผู้สร้าง, สถาปนิก","She's a London-based architect and interior designer."],
["Abolish","(v) ล้มเลิก, ทำลาย","She campaigned to abolish the death penalty altogether."],
["Acceleration","(n) การเร่ง, การเพิ่มความเร็ว","There has been a rapid acceleration in the growth of industry."],
["Accelerate","(v) เร่ง, เร่งให้เกิดขึ้น","The pace of change has begun to accelerate."],
["Appoint","(v) แต่งตั้ง, กำหนดวัน","They have appointed a new head teacher at my son's school."],
["Appeal","(n) ร้องขอ, ขออุทรณ์","Police appealed to the public for information about the crime."],
["Accountant","(n) นักบัญชี","We talked to the company's chief accountant."],
["Amend","(v) แก้ไข","Parliament will vote to amend the constitution."],
["Apprise","(v) แจ้งข่าว","He saw no reason to apprise the committee of what had happened."],
["Appealing","(adj) ซึ่งดึงดูดใจ, มีเสน่ห์","The large salary made their offer even more appealing to him."],
["Anticipate","(v) คาดการณ์","They anticipate their needs for the next quarter."],
["Access","(n) ทางเข้า","The police gained access through a broken window."],
["Analogy","(n) การเปรียบเทียบ","The teacher drew an analogy between the human heart and a pump."],
["Anarchy","(n) อนาธิปไตย","There was complete anarchy in the classroom when their usual teacher was away."],
["Antagonism","(n) การต่อต้าน","The new rules will create a lot of antagonism."],
["Arrogance","(n) ความเย่อหยิ่ง","He has a reputation for rudeness and intellectual arrogance."],
["Agitate","(v) ปั่นป่วน, ปลุกระดม","This remark seemed to agitate her guest."],
["Acid rain","(n) ฝนกรด","Sulphur, falling as acid rain, is killing fish in the Great Lakes."],
["Aggregate","(v) รวบรวม","The scores were aggregated with the first round totals to decide the winner."],
["Ancient","(adj) โบราณกาล","Archaeologists are excavating the ruined temples of this ancient civilization."],
["Aggravate","(v) ทำให้แย่ลง","The government's actions will only aggravate the problem."],
["Acquire","(v) ได้มา","I would love to apply the newly acquired skills to a job that I enjoy."],
["Acquisitive","(adj) โลภ","It is an acquisitive company looking for ways to expand."],
["Adhere","ติดแน่น, ยึดแน่น","Clean the surface first, or the paint will not adhere."],
["Avoidance","(n) การเลี่ยง","A person's health improves with the avoidance of stress."],
["Avoid","(v) หลีกเลี่ยง","They are anxious to avoid any further misunderstandings."],
["Acknowledge","(adj) เป็นที่รับรู้","I have to acknowledge the fact that I am partly responsible."],
["Archeology","(n) โบราณคดี","They've got it on display at the National Archeology Museum in Athens."],
["Anomaly","(n) ความแปลก, ความผิดปกติ","There are areas of anomaly in the report."],
["Agriculture","(n) วิชาการเกษตร","The number of people employed in agriculture has fallen in the last decade."],
["Adjoin","(v) ใกล้ชิด, ติดกับ","A barn adjoins the farmhouse."],
["Alliance","(n) สหพันธ์, พันธมิตร","The Social Democrats are now in alliance with the Greens."],
["Antipathy","(n) ความเกลียดชัง","There was a lot of antipathy between the two doctors."],
["Attitude","(n) ทัศนคติ","I try to have a healthy, positive attitude to life."],
["Accumulate","(v) สะสม, พอกพูน","I seem to have accumulated a lot of books."],
["Aversion","(n) การยับยั้ง","People can be helped to overcome their aversion to snakes."],
["Belief","(n) ความเชื่อ","She has lost her belief in God."],
["Bookworm","(n) หนอนหนังสือ","He must be a bookworm to read ten books every day."],
["Buddhism","(n) ศาสนาพุทธ","She became interested in Zen Buddhism."],
["Benefit","(n) ผลประโยชน์","I've had the benefit of a good education."],
["Business","(n) ธุรกิจ","She has set up in business as a hairdresser."],
["Behave","(v) ประพฤติตัว","They behaved very badly towards their guests."],
["Barren","(adj) ไม่มีประโยชน์, แห้งแล้ง","It is a barren wasteland riddled with fire, and ash and dust."],
["Belligerent","(adj) เป็นปฏิปักษ์","He is always very belligerent towards me."],
["Biology","(n) วิชาชีววิทยา","She's a professor of biology at Stanford."],
["Border","(v) ตีขอบเขต","The large garden is bordered by a stream."],
["Broaden","(v) ทำให้กว้างขึ้น, ขยับขยาย","Spending a year working in the city helped to broaden his horizons."],
["Benefactor","(n) ผู้อุปถัมภ์","The equipment was funded by friends and benefactors of the hospital."],
["Barrier","(n) อุปสรรค","The crowd managed to break through the barriers and get onto the pitch."],
["Barter","แลกเปลี่ยนสินค้า","The prisoners tried to barter with the guards for items like writing paper and books."],
["Besiege","(v) โอบล้อมด้วยศัตรู","Paris was besieged for four months and forced to surrender."],
["Budget","(n) งบประมาณ","The work was finished on time and within budget."],
["Banish","(v) เนรเทศ","He was banished to Australia, where he died five years later."],
["Bestow","(v) มอบให้","It was a title bestowed upon him by the king."],
["Byproduct","(n) ผลพลอยได้","One of the by-products of unemployment is an increase in crime."],
["Broad","(adj) กว้าง","He's got broad shoulders."],
["Bleak","(adj) โดยสิ้นหวัง","The future looks bleak for the fishing industry."],
["Breeze","(n) สายลมที่พัดเบา ๆ","I felt the breeze on my face."],
["Blizzard","(n) พายุหิมะ","The blizzard struck the north-east yesterday, causing serious damage."],
["Belittle","(v) ดูถูก, ด้อยค่า","She felt her husband constantly belittled her achievements."],
["Baseball","(n) กีฬาเบสบอล","The old man had talked to the boy about baseball as always."],
["Basketball","(n) บาสเกตบอล","You play basketball for the Los Angeles Lakers."],
["Blemish","(n) ตำหนิ","The police say the suspect has a slight blemish on his left cheek."],
["Clog","(v) ขวาง, กีดขวาง, อัดแน่นไปด้วย","Within a few years the pipes began to clog up."],
["Complexion","(n) ผิว","Her auburn hair and blue eyes, together with a fine complexion, made her extremely attractive."],
["Coal","(n) ถ่านหิน","I put more coal on the fire."],
["Consumerism","(n) บริโภคนิยม","She was appalled by the greed and rampant consumerism she saw in modern society."],
["Contaminate","(v) ปนเปื้อน","He drinking water has become contaminated with lead."],
["Compress","(v) บีบอัด","As more snow fell, the bottom layer was compressed into ice."],
["Comply","(v) เชื่อฟัง, ปฏิบัติตาม","They refused to comply with the UN resolution."],
["Catalogue","(n) บัญชีรายชื่อ","She consulted the museum catalogue."],
["Consensus","(n) ความเห็นส่วนใหญ่","It is difficult to reach a consensus about electoral reform."],
["Centerpiece","(n) ลักษณะหลักๆหรือสำคัญที่สุด","This treaty is the centerpiece of the government's foreign policy."],
["Consistent","(adj) สอดคล้องกัน","His attitude isn't absolutely consistent."],
["Competition","(n) กิจกรรมการแข่งขัน","Hundreds of schools entered the competition."],
["Confront","(v) เผชิญหน้า","He is willing to confront problems directly."],
["Chemical","(adj) ทางเคมี","It seems to be losing its chemical strength."],
["Chronology","(n) ตามลำดับเวลา","We need to establish the exact chronology of this process."],
["Calamity","(n) เหตุการณ์ที่เลวร้าย","His financial help saved the magazine from total calamity."],
["Comfortable","(adj) สะดวกสบาย","The hotel was comfortable enough."],
["Conduct","(v) จัดการ, นำ","They conduct workshops on topics such as women's legal rights."],
["Canoeing","(n) การพายเรือแคนู","Canoeing is an Olympic sport."],
["Conventional","(adj) ประเพณีนิยม, ธรรมดา","He turned out to be a very conventional young man."],
["Convenient","(adj) เหมาะสม","A bicycle is often more convenient than a car in towns."],
["Content","(n) เนื้อหา","We plan to spend more on creating content for the website."],
["Contemplate","(v) ครุ่นคิด","He was very depressed and even contemplated suicide."],
["Confidential","(adj) ที่เป็นความลับ","There is concern about several confidential documents which have gone missing."],
["Contemporary","(adj) ร่วมสมัย","He is among the best-known contemporary artists."],
["Contradict","(v) ขัดแย้ง","The two stories contradict each other."],
["Court","(n) ศาล","She will appear in court tomorrow."],
["Contagion","(n) การติดโรค, การแพร่","There is no risk of contagion"],
["Compulsory","(adj) ที่จำเป็นต้องทำ, ที่บังคับ","The strikers are protesting against the threat of compulsory redundancies."],
["Convert","(v) เปลี่ยน","The hotel is going to be converted into a nursing home."],
["Contract","(n) สัญญา","All employees have a written contract of employment."],
["Cycling","(n) การขี่รถจักรยาน","Cycling is Europe's second most popular sport."],
["Collaborate","(v) ร่วมมือ","She agreed to collaborate with him in writing her biography."],
["Convene","(v) ชุมนุมกัน, รวมตัวกัน","They decided to convene an extraordinary general meeting."],
["Commute","(v) ไปๆมาๆเสมอ","She commutes from Oxford to London every day."],
["Convey","(v) สื่อสาร, ถ่ายทอด, ลำเลียง","He tried desperately to convey how urgent the situation was."],
["Container ship","(n) เรือคอนเทนเนอร์","Shipyards churn out oil tankers, container ships and gas tankers to cater for the demands of globalized industrial production."],
["Canal boat","(n) เรือคลอง","We hired a canal boat in France."],
["Circumscribe","(v) จำกัด","The power of the monarchy was circumscribed by the new law."],
["Civilian","(n) พลเรือน","Two soldiers and one civilian were killed in the explosion."],
["Consume","(v) ใช้, บริโภค","The electricity industry consumes large amounts of fossil fuels."],
["Consumption","(n) การบริโภค, การใช้หมดไป","He was advised to reduce his alcohol consumption."],
["Consumptive","(adj) เกี่ยวกับการบริโภค","Hunting, mining and consumptive activities are not permitted in a National Park."],
["Contemptuous","(adj) อย่างดูถูกผู้อื่น","The company has shown a contemptuous disregard for Henry's complaints."],
["Combustion","(n) กระบวนการการเผาไหม้","Poisonous gases are produced during fossil fuel combustion."],
["Compensation","(n) ค่าทดแทน","The employer has a duty to pay full compensation for injuries received at work."],
["Correlate","(v) มีลักษณะร่วมกัน, สัมพันธ์กัน","The figures do not seem to correlate."],
["Craftsman","(n) ช่างฝีมือ","It is clearly the work of a master craftsman."],
["Coincidence","(n) การเกิดขึ้นพร้อมกัน","By coincidence, we both went to the same school."],
["Corrode","(v) กัดกร่อน","The copper pipework has corroded in places."],
["Charge","(n) ค่าธรรมเนียม","The company will deliver free of charge."],
["Capture","(v) จับตัว","Allied troops captured over 300 enemy soldiers."],
["Council","(n) คณะกรรมการ","The decision still has to be ratified by the full council."],
["Categorize","(v) จัดหมวดหมู่","Her work is difficult to categorize."],
["Category","(n) หมวด","We have created a special category for part-time workers."],
["Classification","(n) การแบ่งประเภท-หมวดหมู่","The material was put into the highest security classification."],
["Compelling","(adj) ที่กระตุ้นความสนใจ","Her latest book makes compelling reading."],
["Coincide","(v) เกิดขึ้นพร้อมกัน","It's a pity our trips to New York don't coincide."],
["Cuisine","(n) ประเภทอาหาร","London offers a wide variety of foreign cuisines."],
["Clench","(v) กำแน่น","His fists clenched slowly until his knuckles were white."],
["Crispness","(n) ความสดชื่น","The salad had lost its crispness."],
["Cast","(v) ขว้าง, เหวี่ยง","The priceless treasures had been cast into the Nile."],
["Conceive","(v) เข้าใจ","I cannot conceive of it!"],
["Conceptual","(adj) ที่เกี่ยวกับกรอบความคิด","He has no conceptual understanding of physics at all."],
["Conception","(n) การเข้าใจ","I had a rather romantic conception of life in the country."],
["Concept","(n) ความคิด, แนวคิด","Culture is a fairly nebulous concept."],
["Circulate","(v) หมุนเวียน, ไหลเวียน","The heart circulates blood around the body."],
["Ceremony","(n) พิธี, พิธีการ","They were married in a simple ceremony."],
["Carve","(v) แกะสลัก","She carves in both stone and wood."],
["Construction","(n) การสร้าง, การก่อสร้าง","Major engineering challenges will be faced during construction."],
["Cherish","(v) รักและใส่ใจ","Children need to be cherished."],
["Certainly","(adv) อย่างแน่นอน","I'm certainly never going there again."],
["Caution","(n) การตักเตือน","The information on the website should be treated with some caution."],
["Dawn","(n) การเริ่มขึ้น, รุ่งอรุณ","This appointment marked the dawn of a productive era in her scientific career."],
["Decision","(n) การตัดสินใจ","Her parents respected her decision not to marry."],
["Debris","(n) ซากปรักหักพัง","She found a pair of children's shoes among the debris."],
["Degree","(n) ความเข้มข้น, ระดับ","Today we rely on computer technology to an unprecedented degree."],
["Decapitate","(v) ตัดหัว","His decapitated body was found floating in a canal."],
["Decorate","(v) ประดับประดา, ตกแต่ง","The family gets together on Christmas Eve to decorate the tree."],
["Decoration","(n) การประดับประดา, เครื่องประดับ","The decorations were taken down and put away for another year."],
["Decorative","(adj) ซึ่งเป็นการประดับ-ตกแต่ง","The style is ornate and highly decorative."],
["Decorator","(n) ช่างตกแต่ง","She became a painter and decorator."],
["Deceptive","(adj) ซึ่งหลอกลวง, อย่างโกหก, ที่สร้างความหลงผิด","The firm was found guilty of publishing a misleading and deceptive advertisement."],
["Decompose","เน่าเปื่อย, ย่อยสลาย","Water decomposes into oxygen and hydrogen."],
["Decree","(v) พิพากษา","They had decreed where I should live and what work I should do."],
["Dedicate","(v) อุทิศ","She dedicates herself to her work."],
["Detain","(v) กักขัง","Prisoners cannot be detained indefinitely without charge."],
["Delicate","(adj) ละเอียดอ่อน","The eye is one of the most delicate organs of the body."],
["Deliberate","(adj) ซึ่งทำอย่างรอบคอบและตั้งใจ","She spoke in a slow and deliberate way."],
["Delegate","(v) มอบให้ทำแทน","I delegate to my assistant whenever possible."],
["Demonstration","(n) การสาธิต","I'll give a quick demonstration of some first-aid techniques."],
["Depict","(v) วาด, พรรณนา","The artist had depicted her lying on a bed."],
["Destruction","(n) การทำลาย, วิธีการทำลาย","Some shopkeepers closed early to prevent the wholesale destruction of their property by the hooligans."],
["Designer","(n) นักออกแบบ","She works as a set designer for the Royal Opera House."],
["Defiant","(adj) แสดงการท้าทาย","She had suddenly turned into a defiant teenager."],
["Dilemma","(n) สภาวะลำบาก","The dilemma facing the country's allies was even more serious."],
["Deform","(v) ทำให้ผิดรูปผิดร่าง","The pressure had caused the wall to deform and buckle."],
["Deferential","(adj) ซึ่งแสดงความเคารพ","He was always deferential towards his mentor."],
["Deforestation","(n) ตัดไม้ทำลายป่า","Deforestation of the Amazon rainforest increased in the early 2000s."],
["Diverse","(adj) ต่างๆนานา,หลากหลาย,แตกต่างกัน,มากมาย","The school is a richly diverse community."],
["Distribute","(v) แจกจ่าย","The newspaper is distributed free."],
["Diagnose","(v) วินิจฉัย (ทางการแพทย์)","His cancer was first diagnosed last year."],
["Driving licence","(n) ใบขับขี่","I got my driving licence when I was eighteen."],
["Discharge","(v) ปลดออก, ขับออก","She was discharged from the police force for bad conduct."],
["Disclose","(v) เปิดเผย","I cannot disclose what we discussed."],
["Duplicate","(v) ทำสำเนา, จำลอง","Please keep the duplicated form and send us the original."],
["Dull","(adj) น่าเบื่อ","The long lectures made the afternoon dull."],
["Disturb","(v) รบกวน","If you get up early, try not to disturb everyone else."],
["Drought","(n) ภัยแล้ง","Farmers are facing ruin after two years of severe drought."],
["Expand","(v) ขยาย","He has plans to expand beyond computer consulting to include engineer training."],
["Exciting","(adj) ที่น่าตื่นเต้น","This is an exciting opportunity for me."],
["Equipment","(n) อุปกรณ์, เครื่องมือ","The local council is supplying new play equipment for the playground."],
["Eject","(v) ขับไล่, ดันออกมา","He was forcibly ejected from the restaurant."],
["Equip","(v) ติดตั้ง, จัดให้มี","She got a bank loan to rent and equip a small workshop."],
["Equally","(adv) อย่างเท่าเทียมกัน","Everyone should be treated equally."],
["Eloquent","(adj) มีวาทศิลป์","He grew very eloquent on the subject."],
["Elite","(n) กลุ่มคนที่ร่ำรวยกว่าคนอื่น","He was an influential member of the ruling elite."],
["Embrace","(v) สวมกอด","She embraced her son warmly."],
["Embarrass","(v) ทำให้อาย","Her questions about my private life embarrassed me."],
["Entitle","(v) ให้สิทธิ","This ticket does not entitle you to travel first class."],
["Egocentric","(adj) ซึ่งเห็นแก่ตัว","He was a supremely egocentric man."],
["Energetic","(adj) ซึ่งมีพลัง","She seems remarkably energetic for a woman her age."],
["Entrepreneur","(n) ผู้ประกอบการ","A creative entrepreneur, he was continually dreaming up new projects."],
["Encourage","(v) ส่งเสริม, สนับสนุน","She encouraged many young writers and artists."],
["Enhance","(v) ปรับปรุงให้ดี","This is an opportunity to enhance the reputation of the company."],
["Encyclopedia","(n) สารานุกรม","I looked the Civil War up in my encyclopedia."],
["Engender","(v) ก่อให้เกิด","The issue engendered controversy."],
["Economy","(adj) ที่ราคาถูกกว่า","Buy the large economy pack."],
["Economics","(n) วิชาเศรษฐศาสตร์","He studied politics and economics at Yale."],
["Economize","(v) ประหยัด","Old people often try to economize on heating, thus endangering their health."],
["Efficiency","(n) ประสิทธิภาพ","She has run the project with great efficiency."],
["Ecosystem","(n) ระบบนิเวศน์","Islands often support delicate ecosystems that evolved without any need for defence."],
["Evolution","(n) วิวัฒนาการ","Finally it was legal to teach evolution everywhere in America."],
["Evaluate","(v) ประเมิน","We need to evaluate how well the policy is working."],
["Eventual","(adj) เกิดขึ้นสุดท้าย","The village school may face eventual closure."],
["Evaporate","(v) ระเหย","Heat until all the water has evaporated."],
["Epidemic","(n) โรคระบาด","An epidemic of measles broke out, and over 200 children died."],
["Erect","(v) ทำให้ตั้งขึ้น, สร้างขึ้น","Keep your trunk erect throughout the exercise."],
["Eradicate","(v) ถอนรากถอนโคน","Smallpox had been completely eradicated from the world."],
["Essentially","(adv) โดยพื้นฐาน","He was, essentially, a teacher, not a manager."],
["Esteem","(n) ความเคารพ","I have great esteem for you."],
["Extravagant","(adj) ฟุ่มเฟือย","She's got very extravagant tastes."],
["Exploit","(v) เอาเปรียบ","The opposition parties will always exploit government problems to their own advantage."],
["Extradite","(v) ส่งผู้ร้ายข้ามเแดน","The British government attempted to extradite the suspects from Belgium."],
["Emerge","(v) ปรากฎ","The swimmer emerged from the lake."],
["Expedition","(n) คณะเดินทาง, การเดินทาง","The expedition returned only two weeks after it had left."],
["Excavate","ขุดค้น","The site has been excavated by archaeologists."],
["Exhibit","(v) แสดง","He longed for the chance to exhibit his work publicly."],
["Ethic","(n) จริยธรรม","He began to question the ethics of his position."],
["Famished","(adj) หิวมาก","When's lunch? I'm famished!"],
["Fabricate","(v) ปลอมแปลง","The prisoner claimed the police had fabricated his confession."],
["Favour","(n) ความช่วยเหลือ","Could you do me a favour and pick up Sam from school today?"],
["Fabulous","(adj) เหลือเชื่อ","The food looks fabulous."],
["Faithful","(adj) เชื่อถือได้","He has been a very faithful friend to me."],
["Federal","(adj) เกี่ยวกับสหพันธรัฐ","There is a plan to introduce random drug testing of federal workers."],
["Fossil fuel","(n) เชื้อเพลิงฟอสซิล","Carbon dioxide is produced in huge amounts when fossil fuels are burned."],
["Finding","(n) ผลของการสืบค้น","This result confirms the findings of many previous studies."],
["Fidelity","(n) ความภักดี","They still maintain fidelity to their religious tradition."],
["Firewood","(n) ฟืน,ไม้ที่ใช้ทำเป็นเชื้อเพลิง","Please, get me some firewood."],
["Finally","(adv) ในที่สุด","I finally managed to get her attention."],
["Forbid","(v) ห้าม","She knew her mother would forbid her going."],
["Forgiveness","(n) การให้อภัย","He begged forgiveness for what he had done."],
["Formulate","(v) สร้างขึ้น, คิดวิธี","This new kitchen cleaner is formulated to cut through grease and dirt."],
["Freight train","(n) รถไฟบรรทุกสินค้า","The freight train just left for Des Moines."],
["Fatigue","(n) ความเหนื่อยล้า","I was dropping with fatigue and could not keep my eyes open."],
["Facilitate","(v) อำนวยความสะดวก","Banking secrecy laws need to be lifted in order to facilitate investigation."],
["Fatal","(adj) ซึ่งทำให้ถึงตาย","If she gets ill again it could prove fatal."],
["Fictional","(adj) แต่งขึ้น, สมมติ","The names of the characters are entirely fictional."],
["Flight attendant","(n) พนักงานต้อนรับบนเครื่องบิน","The flight attendant is handing out some snacks."],
["Fluctuate","(v) ผันผวน","The number of boys at the school fluctuates around 100."],
["Fragrance","(n) กลิ่นหอม, ความหอม, น้ำหอม","The fragrance of lavender filled the room."],
["Fascinate","(v) ทำให้สนใจ หลงใหล","China has always fascinated me."],
["Feminine","(adj) เกี่ยวกับผู้หญิง","Her name fits in with a traditionally feminine image."],
["Fetish","(n) เครื่องราง, ของขลัง","He makes a fetish of his work."],
["Founded","(v) จัดตั้งขึ้น","Her family founded the college in 1992."],
["Furnish","(v) ตกแต่ง","The room was furnished with antiques."],
["Glisten","(v) ส่องแสงระยิบระยับ","The road glistened wet after the rain."],
["Government","(n) รัฐบาล","A new government was formed in September of that year."],
["Gracious","(adj) ซึ่งมีมารยาท","You are the most gracious hostess."],
["Gamble","(v) พนัน, เสี่ยงโชค","She became depressed and began to gamble heavily."],
["Geology","(n) ธรณีวิทยา","Geology is the study of pressure and time."],
["Geography","(n) ภูมิศาสตร์","He likes geography and history."],
["Geometry","(n) เรขาคณิต","The bright boy comprehended the concept of geometry."],
["Generate","(v) ทำให้เกิด","We need someone to generate new ideas."],
["Generation","(n) ยุค, รุ่น","These children seem to have a stronger sense of purpose than the previous generation."],
["Gregarious","(adj) ชอบอยู่เป็นฝูง, ชอบสังคม","We know that some people are born shy and some are born gregarious."],
["The greenhouse effect","(n) ภาวะเรือนกระจก","We are all beginning to experience global warming due to the enhanced greenhouse effect."],
["Global warming","(n) ภาวะโลกร้อน","Global warming will change the patterns of the weather world-wide."],
["Glamour","(n) ความมีเสน่ห์","Hopeful young actors are drawn by the glamour of Hollywood."],
["Growl","(v) คำราม","The dog growled at them."],
["Guardian","(n) ผู้ดูแล","Farmers should be guardians of the countryside."],
["Hamper","(v) ขัดขวาง, สะกัดกั้น","This has hampered the growth of the export market."],
["Humid","(adj) ชื้น","The weather had become very humid."],
["Headquarters","(n) สำนักงานใหญ่","Several companies have their headquarters in the area."],
["Heaven","(n) สวรรค์","I feel like I've died and gone to heaven."],
["Hereditary","(adj) ถ่ายทอดทางพันธุกรรม","Epilepsy is hereditary in her family."],
["History","(n) วิชาประวัติศาสตร์","She studies history of art."],
["Homicide","(n) ฆาตรกรรม","He has been arrested on homicide and assault charges."],
["Hypothesis","(n) สมมติฐาน","Her study is based on the hypothesis that language simplification is possible."],
["Hostile","(adj) ซึ่งเป็นศัตรู","She was openly hostile towards her parents."],
["Humorous","(adj) มีอารมณ์ขัน","The film is delightfully humorous in the best traditions of romantic comedy."],
["Humble","(adj) ถ่อมตัว","She was very humble and apologetic."],
["Haughty","(adj) ซึ่งทระนง, หยิ่งยโส","She threw him a look of haughty disdain."],
["Incontestable","(adj) ที่โต้แย้งไม่ได้","His claim to the land is incontestable."],
["Icky","(adj) น่ารังเกียจ","I touched something icky and it smells terrible."],
["Infect","(v) ติดโรค, ติดเชื้อ","It is not possible to infect another person through kissing."],
["Inform","(v) แจ้งให้ทราบ","He went to inform them of his decision."],
["Induce","(v) ชักชวน, ชักนำ","Large commissions were required to induce banks to participate in deals."],
["Indeed","(adv) อย่างแท้จริง","I was very sad indeed to hear of your father's death."],
["Illuminate","(v) ชี้แจง","The study of language can help to illuminate how the human mind works."],
["Incompatible","(adj) เข้ากันไม่ได้","Scepticism and trust are not necessarily incompatible."],
["Inspect","(v) ตรวจสอบ","Make sure you inspect the goods before signing for them."],
["Intense","(adj) เข้มข้น","The President is under intense pressure to resign."],
["Intensity","(n) ความเข้มข้น, ความรุนแรง","The storm resumed with even greater intensity."],
["Incorporate","(v) รวมเข้าด้วยกัน","The new car design incorporates all the latest safety features."],
["Interview","(n) การสัมภาษณ์","He has an interview next week for the manager's job."],
["Intricate","(adj) ซับซ้อน","The building has intricate geometric designs on several of the walls."],
["Interfere","(v) แทรก, ขัดขวาง","The police are very unwilling to interfere in family problems."],
["Inevitable","(adj) เลี่ยงไม่ได้","It was an inevitable consequence of the decision."],
["Intensive","(adj) เข้มข้น, ละเอียด","The intensive course did marvels for my French."],
["Intact","(adj) ซึ่งไม่เสียหาย","Most of the house remains intact even after two hundred years."]
];
