// ============================================================
// 📖 STORIES — เรื่องสั้นต้นฉบับ (แต่งเอง) — แก้ไฟล์นี้ไฟล์เดียวเพื่อเพิ่มเรื่อง (ดู CONTENT.md)
// { t:ชื่อเรื่อง, text:เนื้อเรื่อง, q:[[คำถาม, คำตอบ, [ตัวเลือก4]], ...] }
// ============================================================
const STORIES = [
{ t:"A Busy Morning",
  text:"Every morning, Anna wakes up at six o'clock. She is always tired because she stays up late watching videos. First, she drinks a cup of hot coffee to feel awake. Then she takes a quick shower and gets dressed for work. Anna works at a small office in the city. The traffic is terrible, so she leaves home early. If she is late, her boss becomes angry. On the train, she reads the news on her phone. Anna hopes that one day she can work from home and sleep a little longer.",
  q:[
  ["What time does Anna wake up?","Six o'clock",["Six o'clock","Seven o'clock","Five o'clock","Eight o'clock"]],
  ["Why is Anna always tired?","She stays up late",["She stays up late","She works at night","She has a baby","She exercises a lot"]],
  ["What does she drink to feel awake?","Hot coffee",["Hot coffee","Cold water","Green tea","Orange juice"]],
  ["Why does she leave home early?","The traffic is terrible",["The traffic is terrible","She likes walking","The train is cheap","Her boss is kind"]],
  ["What does Anna hope for?","To work from home",["To work from home","To buy a new car","To move abroad","To change her job"]]
  ]},
{ t:"The Lost Puppy",
  text:"One rainy afternoon, Tom found a small puppy under a tree. The puppy was wet, cold, and shaking. It had no collar, so Tom could not find its owner. He carried it home and gave it a warm towel and some food. His mother was not happy at first, but the puppy was so cute that she soon smiled. They put up posters around the neighborhood, hoping to find the owner. A week later, nobody had called. Tom was secretly glad. He named the puppy Lucky, and they became best friends.",
  q:[
  ["Where did Tom find the puppy?","Under a tree",["Under a tree","In a box","At the market","Near the river"]],
  ["Why couldn't Tom find the owner?","It had no collar",["It had no collar","It ran away","It was too small","Nobody was home"]],
  ["How did Tom's mother feel at first?","Not happy",["Not happy","Very excited","Scared","Proud"]],
  ["What did they do to find the owner?","Put up posters",["Put up posters","Called the police","Went to the vet","Asked the school"]],
  ["What did Tom name the puppy?","Lucky",["Lucky","Buddy","Max","Coco"]]
  ]},
{ t:"The New Employee",
  text:"David started his new job at a trading company last Monday. He was nervous because he did not know anyone. His manager, Sarah, was very kind and showed him around the office. On his first day, David learned how to write emails to clients and check the inventory. The work was harder than he expected, but his colleagues were friendly and helped him. By Friday, David felt much more confident. He realized that a good team makes a difficult job much easier. That weekend, he slept well for the first time in days.",
  q:[
  ["When did David start his job?","Last Monday",["Last Monday","Last Friday","This morning","Two weeks ago"]],
  ["Why was David nervous?","He didn't know anyone",["He didn't know anyone","He was late","He lost his phone","He hated the job"]],
  ["Who showed him around the office?","His manager Sarah",["His manager Sarah","A client","His father","A security guard"]],
  ["What made the difficult job easier?","Friendly colleagues",["Friendly colleagues","A higher salary","A short commute","A new computer"]],
  ["How did David feel by Friday?","More confident",["More confident","Very bored","Angry","Sleepy"]]
  ]},
{ t:"The Weekend Market",
  text:"Every Saturday, Mai visits the weekend market near her house. The market is always crowded and full of colors. She loves the smell of fresh fruit and street food. Her favorite stall sells cheap clothes and handmade bags. Mai is good at bargaining, so she never pays the first price. Last week, she bought a beautiful scarf for half the price. After shopping, she sits at a small cafe and enjoys a cold drink. For Mai, the market is not only a place to shop, but also a place to relax and watch people.",
  q:[
  ["When does Mai visit the market?","Every Saturday",["Every Saturday","Every Sunday","Every morning","Once a month"]],
  ["What is Mai good at?","Bargaining",["Bargaining","Cooking","Singing","Driving"]],
  ["What did she buy last week?","A scarf",["A scarf","A bag","A hat","A dress"]],
  ["Where does she go after shopping?","A cafe",["A cafe","The gym","Her office","The park"]],
  ["Besides shopping, what is the market for Mai?","A place to relax",["A place to relax","A place to work","A place to study","A place to exercise"]]
  ]},
{ t:"Learning to Cook",
  text:"When Lisa moved into her own apartment, she could not cook at all. She ate instant noodles almost every night. One day, she felt tired and unhealthy, so she decided to learn. She watched videos online and followed simple recipes. Her first attempt was a disaster: the rice was burnt and the soup was too salty. But Lisa did not give up. She practiced every weekend and slowly improved. Now she can cook many delicious meals and even invites friends for dinner. Cooking has become her favorite hobby, and she feels much healthier than before.",
  q:[
  ["What did Lisa eat almost every night at first?","Instant noodles",["Instant noodles","Fried rice","Salad","Sandwiches"]],
  ["Why did she decide to learn to cook?","She felt unhealthy",["She felt unhealthy","She lost her job","A friend asked her","She won a prize"]],
  ["How was her first attempt?","A disaster",["A disaster","Perfect","Expensive","Quick"]],
  ["When did she practice?","Every weekend",["Every weekend","Every morning","Once a year","Never"]],
  ["How does she feel now?","Much healthier",["Much healthier","More tired","Bored","Hungry"]]
  ]},


// ===== Level 3-5 (ชีวิตจริง + คละแนว | เล่าเรียงเวลา ประโยคชัด ความยากอยู่ที่คำถาม) =====
{ t:"The Group Project", lv:3,
  text:"Nan had four people in her group. Marco talked the most. In the first meeting, he told everyone about the high mark he got last term. Nobody had asked him about it. Two students in the group agreed with everything Marco said. The fourth student was a quiet girl named Linh. For two weeks, Marco said he was writing the introduction. He never sent it. Three days before the deadline, Marco sent one short message. He said he had a family emergency. Then he stopped answering his phone. Nan was afraid. She had three days and no introduction. That night, Linh sent her a file. It was a finished outline with six pages of notes. Linh wrote, “I started this last week. I thought we might need it.” On presentation day, Marco came back. He spoke first and explained the project very well. The teacher gave him the highest mark in the group. Linh did not say anything. She looked at Nan and smiled a little.",
  q:[
  ["Why did Linh start the work a week early?","She expected that Marco would not finish his part",["She expected that Marco would not finish his part","She wanted to get the highest mark","The teacher asked her to do it","She had no other homework that week"],"inference"],
  ["Why did the two other students agree with everything Marco said?","They were influenced by how confident he sounded",["They were influenced by how confident he sounded","They had read his work and liked it","They were his close friends from home","They wanted to finish the meeting quickly"],"inference"],
  ["What does Linh's small smile at the end suggest?","She and Nan both understood the truth without saying it",["She and Nan both understood the truth without saying it","She was happy that Marco got a good mark","She was about to tell the teacher everything","She did not understand what had happened"],"inference"],
  ["Why did Marco talk about his mark in the first meeting?","He wanted the group to think he was the strongest member",["He wanted the group to think he was the strongest member","The teacher had asked him to share it","He was answering Nan's question","He wanted to help the others improve"],"inference"],
  ["What is the main idea of this passage?","The person who does the most work is not always the one who is praised",["The person who does the most work is not always the one who is praised","Group projects are harder than individual projects","Students should never trust their classmates","Quiet students always work harder than loud ones"],"main"]
  ]},
{ t:"The Phone Shop", lv:3,
  text:"May went to the shop to buy a charger. A charger cost about two hundred pesos. The assistant met her at the door. He did not show her the chargers. He walked her to a new phone and began explaining its features. May said she only wanted a charger. The assistant said the phone had a special price today. He said the price would end at closing time. He said this three times. May told him the phone was too expensive for her. The assistant laughed. He said that smart people do not worry about small amounts of money. May's face felt hot. She picked up the phone box and looked at it carefully. There was no warranty card inside. There was only a thin piece of paper. The paper had no shop name and no address on it. May put the box down. “I'll think about it,” she said. The assistant stopped smiling. He turned and walked to another customer. He did not say goodbye. May left and bought her charger at a small shop next door for one hundred and eighty pesos.",
  q:[
  ["Why did the assistant stop smiling?","He realised she would not buy the phone",["He realised she would not buy the phone","He was embarrassed about the missing card","He was angry that she touched the box","He had to close the shop soon"],"inference"],
  ["Why did May look at the box more carefully after the assistant laughed?","His behaviour made her suspicious of the shop",["His behaviour made her suspicious of the shop","She wanted to check the phone's colour","She was looking for the price tag","She wanted to find the charger inside"],"inference"],
  ["What was strange about the paper inside the box?","A real shop would print its name and address on it",["A real shop would print its name and address on it","It was written in a foreign language","It was too small to read","It listed the wrong price"],"inference"],
  ["Why does the writer tell us the price May paid next door?","To show that the assistant's shop was not a good deal",["To show that the assistant's shop was not a good deal","To show that May was very poor","To explain why chargers are cheap","To prove the first shop was closed"],"inference"],
  ["What is the best lesson from this passage?","When a seller pushes you to hurry, slow down and check",["When a seller pushes you to hurry, slow down and check","Never buy anything from a large shop","New phones are always too expensive","Always ask for a discount before buying"],"main"]
  ]},
{ t:"Sunday Call", lv:4,
  text:"Ploy and her boyfriend Beam talked on a video call every Sunday at eight o'clock. Ploy was studying in Cebu. Beam was working in Bangkok. Last Sunday, Beam was very tired. He had worked six days that week and had slept only four hours the night before. Ploy started first. She said her teacher had corrected her in front of the whole class. She said she had felt stupid all day. Beam said, “At least you get to study. I work every day.” Ploy did not answer. Beam did not notice. He talked about his own week for two more minutes. Then he stopped and looked at the screen. Ploy's face was very still. “I'm tired,” she said. “I'm going to sleep.” Her voice was flat. She ended the call. Beam sat and looked at the dark phone for a long time. Then he sent a message: “I'm sorry. Tell me about your teacher tomorrow. I want to hear it.” Ploy read the message at midnight. She did not answer that night. She did not delete it either.",
  q:[
  ["Why did Ploy stop talking after Beam's answer?","She felt that he had treated her problem as unimportant",["She felt that he had treated her problem as unimportant","She could not hear him clearly","She was angry that he worked six days","She had already finished her story"],"inference"],
  ["What does Ploy's flat voice tell us?","She was hurt but did not want to argue",["She was hurt but did not want to argue","She was calm and no longer upset","She was too sleepy to speak normally","She was joking with him"],"inference"],
  ["Why did Beam say “At least you get to study”?","He was tired and compared her situation to his own",["He was tired and compared her situation to his own","He wanted to remind her that school is expensive","He thought she was going to quit school","He was proud of her studies"],"inference"],
  ["Why did Ploy keep the message instead of deleting it?","She was still hurt but did not want to end things",["She was still hurt but did not want to end things","She wanted to show it to her teacher","She had fallen asleep before deleting it","She had already forgiven him completely"],"inference"],
  ["What did Beam finally understand?","She wanted him to listen, not to compare",["She wanted him to listen, not to compare","She wanted him to call more often","She wanted him to find an easier job","She wanted to visit him in Bangkok"],"main"]
  ]},
{ t:"The Parcel Downstairs", lv:4,
  text:"A parcel arrived for room 3B on a Monday. Nobody took it inside. Mrs. Reyes owned the boarding house, and she saw it every morning. On the first day she told herself it was not her business. On the fourth day she began to wonder. Maybe the young man had gone home for a holiday. Maybe someone in his family was sick. On the seventh day she looked at the box more closely. There was an address, but there was no name and no sender. Twice she picked up her phone to call his parents. Twice she put it down. Her mother used to say that curiosity killed the cat. On the ninth evening she knocked on his door. Nobody answered. She knocked again and said through the door that she had cooked too much rice. The door opened a few centimetres. The young man had not shaved for a week. He looked at the parcel and then looked away. “It's from my father,” he said. “He died in March.” Mrs. Reyes did not ask anything more. She gave him the bowl of rice and went back downstairs.",
  q:[
  ["Why did Mrs. Reyes talk about rice instead of asking about the parcel?","It gave her a kind reason to check on him without prying",["It gave her a kind reason to check on him without prying","She wanted him to pay for the food","She had really cooked too much by accident","She was collecting the rent that evening"],"inference"],
  ["Why did the young man look away from the parcel?","Seeing it reminded him that his father was gone",["Seeing it reminded him that his father was gone","He thought something dangerous was inside","He had never seen the parcel before","He was angry at the delivery company"],"inference"],
  ["Why did Mrs. Reyes put her phone down twice?","She was not sure she had the right to interfere",["She was not sure she had the right to interfere","She did not know his parents' number","She was afraid of the young man","She forgot what she wanted to say"],"inference"],
  ["Why has the parcel stayed outside for nine days?","Opening it would force him to accept his father's death",["Opening it would force him to accept his father's death","He was waiting for his family to come","He did not know it was there","He was planning to send it back"],"inference"],
  ["Why did Mrs. Reyes stop asking questions at the end?","She understood that he needed care, not questions",["She understood that he needed care, not questions","She was in a hurry to cook dinner","She was afraid of hearing more bad news","She had already guessed the whole story"],"main"]
  ]},
{ t:"Why Cats Land on Their Feet", lv:4,
  text:"Almost everyone has seen a cat fall and land safely on its feet. Scientists call this the righting reflex, and it works in a fixed order. First the cat turns its head. Then it turns the front half of its body. Then the back half follows. Last, the cat opens its legs and bends them, so its legs absorb the shock of landing. All of this happens in less than one second. The cat does not decide to do it. The movement is an instinct, and kittens can already do it at seven weeks old. There is one surprising part. A cat that falls from a low window is often hurt more badly than a cat that falls from a high window. From a low window, the cat does not have enough time to finish turning. From a high window, the cat has time to turn, and it also has time to spread its legs wide. Wide legs slow the cat down, like a small parachute. Doctors in New York studied cats that fell from tall buildings. Many of the cats that fell from the seventh floor or higher walked away with no serious injury.",
  q:[
  ["Why can a fall from a high window be safer for a cat than a fall from a low window?","The cat has enough time to finish turning and spread its legs",["The cat has enough time to finish turning and spread its legs","High windows are usually above soft ground","The cat becomes more careful when it is frightened","Cats fall more slowly from tall buildings"],"inference"],
  ["What does the passage mean when it says the cat “does not decide to do it”?","The movement happens automatically, without thinking",["The movement happens automatically, without thinking","The cat is unconscious while it falls","The cat has been trained by its mother","The cat is too frightened to move"],"vocab"],
  ["Why do wide legs help the cat?","They slow the cat down before it lands",["They slow the cat down before it lands","They help the cat turn its head faster","They protect the cat's head from hitting the ground","They make the cat look bigger"],"inference"],
  ["What can we infer from the fact that kittens can do this at seven weeks old?","The ability comes naturally and does not need to be learned",["The ability comes naturally and does not need to be learned","Kittens are stronger than adult cats","Mother cats teach this skill very early","Young cats fall more often than old cats"],"inference"],
  ["What is the main idea of this passage?","A cat lands safely because of a fast, automatic set of movements",["A cat lands safely because of a fast, automatic set of movements","Cats should not be allowed near open windows","Scientists in New York study many kinds of animals","Falling is more dangerous for kittens than for adult cats"],"main"]
  ]},
{ t:"The Interview", lv:5,
  text:"The hotel advertisement said the job required three years of experience. Dao had two years. She applied anyway. In the interview, the manager asked her one question about angry customers. “What would you do if a guest shouted at you about a mistake that was not yours?” Dao said she would say sorry first and explain later. She said that a person who feels blamed stops listening. The manager wrote something in his notebook. Then he asked why she had left her last company after only eleven months. Dao thought about the safe answer. She could say she was looking for a new challenge. Instead she told the truth. She said her old company had promoted her too fast, that she had not been ready, and that she had learned the difference between wanting a job and being able to do it. The room was quiet for a moment. Dao walked out and told her friend that she had ruined the interview. Two days later the hotel called and offered her the job. The manager told her that every other person had answered the second question with the same sentence about new challenges.",
  q:[
  ["Why did the manager remember Dao's second answer?","She told an honest truth while everyone else gave a prepared answer",["She told an honest truth while everyone else gave a prepared answer","She had the most experience of all the candidates","She explained her old job in the most detail","She avoided answering the question"],"inference"],
  ["Why did Dao think she had ruined the interview?","She had admitted a weakness out loud",["She had admitted a weakness out loud","She had arrived late to the interview","She had argued with the manager","She had forgotten to mention her experience"],"inference"],
  ["What did Dao mean by “the difference between wanting a job and being able to do it”?","Being ready for a role is not the same as wanting it",["Being ready for a role is not the same as wanting it","Ambitious people are usually poor workers","Ability only matters after you are promoted","Her old company had treated her unfairly"],"vocab"],
  ["Why would Dao say sorry before explaining?","An angry person cannot listen to an explanation yet",["An angry person cannot listen to an explanation yet","The guest is always correct","Saying sorry is faster than explaining","She wanted to avoid talking about the mistake"],"inference"],
  ["What is the main idea of this passage?","Being honest about your own limits can be worth more than experience",["Being honest about your own limits can be worth more than experience","Job advertisements should not list requirements","Most people lie during job interviews","Leaving a job early will damage your career"],"main"]
  ]},

// ===== ตัวอย่างเต็มรูปแบบตามพิมพ์เขียวข้อสอบ (300 คำ / 8 ข้อ / มีเฉลยอธิบาย) =====
{ t:"The Corner Table", lv:4, hideTitle:true,
  text:"Nok had been in Cebu for two months, and she still ate lunch alone. Her classmates went to the mall across the street, but the food there cost three times more. Her family had saved for two years to send her to the language school. She counted every peso.\n\nBehind the school there was a small carinderia with four plastic tables. An old woman named Aling Rosa cooked there every day. Nok always ordered the same thing: one cup of rice and the cheapest vegetable dish. She sat at the corner table and practised her English homework while she ate.\n\nOne Tuesday, Aling Rosa put a plate down in front of her. There was twice as much rice as usual, and a piece of fried fish on top. Nok looked up. “I did not order this,” she said. “I know,” Aling Rosa answered, and she walked back to the kitchen. Nok reached for her wallet. Aling Rosa did not turn around. “Sit down and eat,” she said. “The fish will get cold.”\n\nIt happened again on Thursday, and again the next week. In the second month, Nok finally asked why. Aling Rosa wiped her hands on her apron and looked at the street for a moment. She said that her own daughter had studied in Singapore for three years. “She called me once and told me she was eating instant noodles every night,” Aling Rosa said. “I could not send her food. I was too far away.”\n\nNok did not know what to say, so she said thank you. The next morning she arrived twenty minutes early. She wiped the four tables and carried the chairs outside before class. Aling Rosa watched her from the kitchen door and did not stop her.",
  q:[
  ["Based on paragraph 1, we can tell that Nok ate lunch alone mainly because","she was being careful with her family's money",["she was being careful with her family's money","she did not like her classmates","the mall was too far from the school","she preferred to study while eating"],"inference","ย่อหน้า 1 บอกว่าครอบครัวเก็บเงิน 2 ปีส่งเธอเรียน และเธอ “นับทุกเปโซ” ส่วนอาหารในห้างแพงกว่า 3 เท่า จึงเป็นเรื่องเงิน ไม่ใช่เพราะไม่ชอบเพื่อน"],
  ["According to the passage, what did Nok usually order?","Rice and the cheapest vegetable dish",["Rice and the cheapest vegetable dish","Fried fish and rice","Instant noodles","Food from the mall"],"detail","ย่อหน้า 2 เขียนตรงๆ ว่าเธอสั่งข้าว 1 ถ้วยกับผัดผักที่ถูกที่สุดเป็นประจำ ส่วนปลาทอดคือของที่ป้าให้ทีหลัง ไม่ใช่ของที่เธอสั่ง"],
  ["As used in paragraph 2, the word “carinderia” most nearly means","a small local eating place",["a small local eating place","a language school","a shopping mall","a private kitchen at home"],"vocab","เดาจากบริบทรอบคำ: มีโต๊ะพลาสติก 4 ตัว มีคนทำอาหารขายทุกวัน มีคนมาสั่งอาหาร → แปลว่าร้านอาหารเล็กๆ ไม่ต้องรู้คำนี้มาก่อนก็เดาได้"],
  ["Why did Aling Rosa say “The fish will get cold”?","To stop Nok from paying without refusing her directly",["To stop Nok from paying without refusing her directly","Because the kitchen was cold that day","Because she wanted Nok to leave quickly","Because she had cooked the fish too early"],"inference","ดูลำดับเหตุการณ์: นกล้วงกระเป๋าเงิน → ป้าไม่หันมา → ป้าพูดเรื่องปลาจะเย็น = เปลี่ยนเรื่องเพื่อไม่ให้จ่าย เป็นการปฏิเสธแบบไม่ทำให้อีกฝ่ายเสียหน้า"],
  ["Why did Aling Rosa give Nok extra food?","Nok reminded her of her own daughter far from home",["Nok reminded her of her own daughter far from home","She had cooked too much food that day","She wanted Nok to become a regular customer","Nok had helped her clean the tables"],"inference","ย่อหน้า 4 ป้าเล่าว่าลูกสาวไปเรียนสิงคโปร์แล้วกินมาม่าทุกคืน และป้า “ส่งอาหารไปให้ไม่ได้” → ป้าทำให้นกในสิ่งที่ทำให้ลูกตัวเองไม่ได้ ข้อ D ผิดเพราะนกเช็ดโต๊ะ *หลังจาก* ได้อาหารแล้ว"],
  ["Why did Nok come to the carinderia early the next morning?","To thank Aling Rosa in a way Aling Rosa would accept",["To thank Aling Rosa in a way Aling Rosa would accept","To ask Aling Rosa for a job","To pay for all the meals she had received","To eat breakfast before class"],"inference","ป้าไม่ยอมรับเงิน (ข้อ C จึงไม่ใช่) นกเลยตอบแทนด้วยแรงแทน และประโยคสุดท้ายที่ป้า “ไม่ห้าม” = ป้ายอมรับการตอบแทนแบบนี้"],
  ["Using the passage as a guide, which of the following are true about Aling Rosa?\nI. She has a daughter who studied abroad.\nII. She refused to take Nok's money.\nIII. She asked Nok to clean the tables.","I and II only",["I only","I and II only","II and III only","I, II, and III"],"detail","I ถูก (ย่อหน้า 4 ลูกสาวเรียนสิงคโปร์) · II ถูก (ไม่หันมารับเงิน) · III ผิด! เพราะป้าแค่ “มองแล้วไม่ห้าม” ไม่ได้เอ่ยปากขอ — ข้อแบบนี้ต้องอ่านให้ละเอียดว่า ‘ไม่ห้าม’ ≠ ‘ขอให้ทำ’"],
  ["Which of the following would be the best title for this passage?","The Extra Plate",["The Extra Plate","How to Save Money in Cebu","Studying in Singapore","Aling Rosa's Restaurant"],"main","ชื่อเรื่องที่ดีต้องครอบคลุมทั้งเรื่อง — แก่นคือ ‘จานพิเศษ’ ที่นำไปสู่ความสัมพันธ์ ส่วน B พูดถึงแค่ย่อหน้าแรก, C พูดถึงแค่ประโยคเดียว, D กว้างเกินและร้านไม่ใช่ประเด็นหลัก"]
  ]},
];
