// ============================================================
// 📖 STORIES — เรื่องสั้นต้นฉบับ (แต่งเอง) — แก้ไฟล์นี้ไฟล์เดียวเพื่อเพิ่มเรื่อง (ดู CONTENT.md)
// { t:ชื่อเรื่อง, text:เนื้อเรื่อง, q:[[คำถาม, คำตอบ, [ตัวเลือก4]], ...] }
// ============================================================
const STORIES = [
{ t:"A Busy Morning",
  text:"Every morning, Anna wakes up at six o'clock. She is always tired because she stays up late watching videos. First, she drinks a cup of hot coffee to feel awake. Then she takes a quick shower and gets dressed for work. Anna works at a small office in the city. The traffic is terrible, so she leaves home early. If she is late, her boss becomes angry. On the train, she reads the news on her phone. Anna hopes that one day she can work from home and sleep a little longer.",
  q:[
  ["What time does Anna wake up?","Six o'clock",["Six o'clock","Seven o'clock","Five o'clock","Eight o'clock"]],
  ["Why is Anna always tired?","She stays up late",["She stays up late","She works at night","She has a baby","She exercises a lot"]],
  ["What does she drink to feel awake?","Hot coffee",["Hot coffee","Cold water","Green tea","Orange juice"]],
  ["Why does she leave home early?","The traffic is terrible",["The traffic is terrible","She likes walking","The train is cheap","Her boss is kind"]],
  ["What does Anna hope for?","To work from home",["To work from home","To buy a new car","To move abroad","To change her job"]]
  ]},
{ t:"The Lost Puppy",
  text:"One rainy afternoon, Tom found a small puppy under a tree. The puppy was wet, cold, and shaking. It had no collar, so Tom could not find its owner. He carried it home and gave it a warm towel and some food. His mother was not happy at first, but the puppy was so cute that she soon smiled. They put up posters around the neighborhood, hoping to find the owner. A week later, nobody had called. Tom was secretly glad. He named the puppy Lucky, and they became best friends.",
  q:[
  ["Where did Tom find the puppy?","Under a tree",["Under a tree","In a box","At the market","Near the river"]],
  ["Why couldn't Tom find the owner?","It had no collar",["It had no collar","It ran away","It was too small","Nobody was home"]],
  ["How did Tom's mother feel at first?","Not happy",["Not happy","Very excited","Scared","Proud"]],
  ["What did they do to find the owner?","Put up posters",["Put up posters","Called the police","Went to the vet","Asked the school"]],
  ["What did Tom name the puppy?","Lucky",["Lucky","Buddy","Max","Coco"]]
  ]},
{ t:"The New Employee",
  text:"David started his new job at a trading company last Monday. He was nervous because he did not know anyone. His manager, Sarah, was very kind and showed him around the office. On his first day, David learned how to write emails to clients and check the inventory. The work was harder than he expected, but his colleagues were friendly and helped him. By Friday, David felt much more confident. He realized that a good team makes a difficult job much easier. That weekend, he slept well for the first time in days.",
  q:[
  ["When did David start his job?","Last Monday",["Last Monday","Last Friday","This morning","Two weeks ago"]],
  ["Why was David nervous?","He didn't know anyone",["He didn't know anyone","He was late","He lost his phone","He hated the job"]],
  ["Who showed him around the office?","His manager Sarah",["His manager Sarah","A client","His father","A security guard"]],
  ["What made the difficult job easier?","Friendly colleagues",["Friendly colleagues","A higher salary","A short commute","A new computer"]],
  ["How did David feel by Friday?","More confident",["More confident","Very bored","Angry","Sleepy"]]
  ]},
{ t:"The Weekend Market",
  text:"Every Saturday, Mai visits the weekend market near her house. The market is always crowded and full of colors. She loves the smell of fresh fruit and street food. Her favorite stall sells cheap clothes and handmade bags. Mai is good at bargaining, so she never pays the first price. Last week, she bought a beautiful scarf for half the price. After shopping, she sits at a small cafe and enjoys a cold drink. For Mai, the market is not only a place to shop, but also a place to relax and watch people.",
  q:[
  ["When does Mai visit the market?","Every Saturday",["Every Saturday","Every Sunday","Every morning","Once a month"]],
  ["What is Mai good at?","Bargaining",["Bargaining","Cooking","Singing","Driving"]],
  ["What did she buy last week?","A scarf",["A scarf","A bag","A hat","A dress"]],
  ["Where does she go after shopping?","A cafe",["A cafe","The gym","Her office","The park"]],
  ["Besides shopping, what is the market for Mai?","A place to relax",["A place to relax","A place to work","A place to study","A place to exercise"]]
  ]},
{ t:"Learning to Cook",
  text:"When Lisa moved into her own apartment, she could not cook at all. She ate instant noodles almost every night. One day, she felt tired and unhealthy, so she decided to learn. She watched videos online and followed simple recipes. Her first attempt was a disaster: the rice was burnt and the soup was too salty. But Lisa did not give up. She practiced every weekend and slowly improved. Now she can cook many delicious meals and even invites friends for dinner. Cooking has become her favorite hobby, and she feels much healthier than before.",
  q:[
  ["What did Lisa eat almost every night at first?","Instant noodles",["Instant noodles","Fried rice","Salad","Sandwiches"]],
  ["Why did she decide to learn to cook?","She felt unhealthy",["She felt unhealthy","She lost her job","A friend asked her","She won a prize"]],
  ["How was her first attempt?","A disaster",["A disaster","Perfect","Expensive","Quick"]],
  ["When did she practice?","Every weekend",["Every weekend","Every morning","Once a year","Never"]],
  ["How does she feel now?","Much healthier",["Much healthier","More tired","Bored","Hungry"]]
  ]},

// ===== Level 4-5 (ยากขึ้น: อนุมาน / เดาความหมายจากบริบท / จับใจความ) =====
{ t:"The Pushy Salesman", lv:4,
  text:"Marisa had promised herself she would only look. The shop assistant, however, had other plans. He followed her from shelf to shelf, listing features she had never asked about and repeating that the discount would end at closing time. When she mentioned the price, he laughed and said that only foolish people worried about such small amounts. Marisa felt her face grow warm. She had walked in wanting a simple blender; now she was holding a machine with eleven settings she would never use. Something made her look for the warranty card. She found only a thin sheet of paper with no company address printed on it. That was the clue she needed. A shop that is certain of its product does not hide where that product came from. “I'll think about it,” she said. The assistant's smile vanished, and he turned to the next customer without another word. Walking home with empty hands, Marisa understood something that annoyed her: the discount had never been the real offer. The rush had been the product.",
  q:[
  ["What is the main lesson of this passage?","Pressure to decide quickly is often a warning sign",["Pressure to decide quickly is often a warning sign","Blenders with many settings are a waste of money","Shop assistants are paid too little","Warranty cards protect every buyer"],"main"],
  ["Why did the assistant's smile vanish?","He realized she would not buy, so she was no longer useful to him",["He realized she would not buy, so she was no longer useful to him","He was embarrassed about the missing address","He had been told to serve one customer at a time","He was insulted by her opinion of the price"],"inference"],
  ["“That was the clue she needed” refers to what?","The warranty paper with no company address",["The warranty paper with no company address","The eleven settings on the blender","The salesman's loud laugh","The discount ending at closing time"],"vocab"],
  ["What can we infer about Marisa before she entered the shop?","She had not planned to buy anything that day",["She had not planned to buy anything that day","She had already saved money for a blender","She knew the assistant personally","She had visited the shop many times"],"inference"],
  ["What does the last sentence, “The rush had been the product,” suggest?","The seller was really selling urgency, not the blender",["The seller was really selling urgency, not the blender","The blender was made in a hurry","She regretted leaving so quickly","Discounts always expire too fast"],"tone"]
  ]},
{ t:"What the Coach Never Said", lv:4,
  text:"For eleven years, Coach Ruiz never gave a speech after a loss. The players expected an earful; instead he handed out water bottles and asked about their families. The spectators found this strange. One local reporter wrote that the team lacked fire because the coach refused to shout. That season, the team lost the final by a single point. As the winners celebrated, Ruiz walked his players along the line to shake every opposing hand. One young player, still crying, tried to pull away. Ruiz held his shoulder and said quietly, “Anyone can be gracious after winning. That costs nothing.” Three years later, four of those players had become coaches themselves. None of them could recall a single thing Ruiz said about tactics. Every one of them remembered the walk along that line. The reporter, by then retired, wrote a short piece admitting he had measured the wrong thing. Fire, he decided, is not the same as noise.",
  q:[
  ["What does the passage mainly suggest about good coaching?","Character taught by example outlasts tactical instruction",["Character taught by example outlasts tactical instruction","Losing teaches more than winning does","Coaches should never criticize their players","Young athletes need strict discipline to improve"],"main"],
  ["Why did Ruiz make his players shake hands after losing?","To show that dignity matters most when it is hardest",["To show that dignity matters most when it is hardest","To follow a rule set by the league","To delay the players' return to the locker room","To impress the watching reporter"],"inference"],
  ["What did the reporter mean by “he had measured the wrong thing”?","He had judged the coach by volume instead of by influence",["He had judged the coach by volume instead of by influence","He had reported the final score incorrectly","He had counted the wrong number of losses","He had confused two different coaches"],"vocab"],
  ["What can we infer from the players remembering the handshake but not the tactics?","Lessons about behavior stayed with them longer than instructions",["Lessons about behavior stayed with them longer than instructions","Ruiz never actually taught them any tactics","The players had poor memories","The final match was not important to them"],"inference"],
  ["Which word best describes the author's attitude toward Coach Ruiz?","Admiring",["Admiring","Doubtful","Amused","Indifferent"],"tone"]
  ]},
{ t:"The Parcel That Waited", lv:4,
  text:"The parcel had been sitting by the door of apartment 6B for nine days. Mrs. Okonjo noticed it on the first morning and told herself it was none of her business. By the fourth day she had begun inventing explanations: a holiday, a hospital, a family emergency. By the seventh, her instinct told her that something was wrong, though she could not say what. There was no name on the box, only a printed address and a small line where a sender's details should have been. Twice she reached for the building manager's number and twice she stopped, hearing her mother's voice: curiosity killed the cat. On the ninth evening she knocked. No answer. She knocked again and, feeling foolish, called out that she had made too much soup. The door opened a few centimetres. The young man behind it had not shaved in a week, and his eyes moved past her to the parcel as though it were an animal that might bite. “It's from my father,” he said. “He died in March.” Mrs. Okonjo did not ask another question. She simply held out the bowl.",
  q:[
  ["What is the main point of this passage?","Knowing when to stop asking can be a form of kindness",["Knowing when to stop asking can be a form of kindness","Neighbours should report suspicious packages","Grief makes people forget practical tasks","Old sayings are usually wrong"],"main"],
  ["Why did Mrs. Okonjo mention soup instead of the parcel?","It gave her a gentle reason to knock without prying",["It gave her a gentle reason to knock without prying","She wanted to sell him food","She had genuinely cooked too much by accident","She was told to check on him by the manager"],"inference"],
  ["What does the comparison of the parcel to “an animal that might bite” suggest about the man?","He feared what opening it would make him feel",["He feared what opening it would make him feel","He believed something dangerous was inside","He had never seen the parcel before","He was angry with the delivery company"],"vocab"],
  ["Why did Mrs. Okonjo stop herself from calling the building manager?","She was unsure whether her concern was really her business",["She was unsure whether her concern was really her business","She did not have the correct phone number","She was afraid of the young man","The manager had refused to help her before"],"inference"],
  ["What can we infer about why the parcel remained unopened?","Opening it would force the man to accept his father's death",["Opening it would force the man to accept his father's death","He was waiting for his family to arrive","He had not noticed it outside his door","He planned to return it to the sender"],"inference"]
  ]},
{ t:"The Tyrant's Quill", lv:5,
  text:"History remembers King Aldric as a tyrant, and history is not wrong. What history rarely mentions is the quill. Aldric could not read. His advisors discovered this early and used it for thirty years, reading him documents that said whatever served them best. The king signed everything, because refusing would have exposed him. When the famine came, the priests brought a decree that raised the grain tax. They read it aloud as a plan for relief. Aldric, oblivious, signed it, and villages emptied. Only near the end of his life did a young scribe, hired for her handwriting rather than her loyalty, read him a document exactly as it was written. The king listened without expression. Then he asked her to read the last thirty years. She did, one decree at a time, for six weeks. When it was finished, Aldric was said to have wept, though no one recorded whether he wept for his people or for his own ruined name. He ordered every child in the kingdom taught to read. The order arrived too late to save him from history, but not too late to change the kingdom.",
  q:[
  ["What is the central irony of the passage?","A cruel ruler's worst damage came from what he did not know",["A cruel ruler's worst damage came from what he did not know","A king who could not read wrote many laws","Priests were more powerful than the king","The scribe was punished for telling the truth"],"main"],
  ["Why did Aldric sign documents without questioning them?","Admitting he could not read would have revealed his weakness",["Admitting he could not read would have revealed his weakness","He trusted his advisors completely","He agreed with everything they proposed","He was too ill to argue with them"],"inference"],
  ["The young scribe was hired “for her handwriting rather than her loyalty.” What does this imply?","She had no reason to protect the advisors' lies",["She had no reason to protect the advisors' lies","She wrote beautifully but worked slowly","She was disloyal to the king himself","She was chosen because she was inexpensive"],"vocab"],
  ["Why does the author mention that no one recorded the reason for Aldric's tears?","To leave his true character genuinely uncertain",["To leave his true character genuinely uncertain","To prove that the story is false","To show that records from that time were lost","To suggest that he never actually cried"],"inference"],
  ["What is the best summary of the final sentence?","His reform came too late for him but still helped others",["His reform came too late for him but still helped others","The kingdom refused to obey his final order","History eventually forgave him","Teaching children to read ended the famine"],"main"]
  ]},
{ t:"Reading the Room", lv:5,
  text:"There is a skill that appears on no résumé and is almost impossible to teach directly. Some call it empathy; others call it reading the room. It is the ability to notice what a group is feeling before anyone says it aloud. Consider a meeting in which a manager asks whether anyone has concerns. The room goes quiet. An inexperienced leader hears agreement and moves on. An experienced one hears the implication in the silence and asks a narrower question instead: not “Any concerns?” but “Which part of this worries you most?” The second question gives permission to speak, and permission is usually what was missing. The difficulty is that this skill can be imitated. A manager may learn the technique, lower his voice, and pause meaningfully, while still having decided everything in advance. Employees detect the difference quickly, and the imitation costs more trust than bluntness ever would. Genuine attention changes what the listener does next; performance changes only how the listener appears. The emphasis, then, should not be on looking attentive. It should be on being willing to hear an answer that ruins your plan.",
  q:[
  ["What is the main argument of the passage?","Real attentiveness must be able to change your decision, or it is only performance",["Real attentiveness must be able to change your decision, or it is only performance","Managers should ask more questions in meetings","Empathy is a skill that cannot be learned","Silence in meetings always means disagreement"],"main"],
  ["Why is “Which part of this worries you most?” more effective than “Any concerns?”","It assumes concerns exist, which makes speaking up feel permitted",["It assumes concerns exist, which makes speaking up feel permitted","It is shorter and easier to understand","It forces employees to criticize the plan","It shows the manager already knows the problem"],"inference"],
  ["In this passage, “the implication in the silence” most nearly means","the unspoken message the quiet is carrying",["the unspoken message the quiet is carrying","the length of the pause before speaking","the manager's hidden intention","the rule that silence means consent"],"vocab"],
  ["Why does the author say imitation “costs more trust than bluntness ever would”?","Being handled dishonestly feels worse than being told the truth harshly",["Being handled dishonestly feels worse than being told the truth harshly","Blunt managers are more popular than quiet ones","Imitation takes more time than speaking directly","Employees prefer leaders who never ask questions"],"inference"],
  ["What can we infer about the author's view of leadership training?","Techniques alone are insufficient without genuine willingness to listen",["Techniques alone are insufficient without genuine willingness to listen","It should be removed from most companies","It works best when taught by experienced managers","It is only useful for inexperienced leaders"],"inference"]
  ]},
{ t:"The Hunter and the Hunted", lv:5,
  text:"The cheetah is the fastest land animal alive, and it fails roughly half the time it hunts. This surprises people, who assume that speed decides the outcome. It does not. What decides the outcome is the last two seconds, when the prey changes direction. A gazelle cannot outrun a cheetah, so it does not try. Instead it turns, sharply and repeatedly, forcing its ferocious pursuer to spend energy correcting rather than chasing. The cheetah's body, built entirely for acceleration, is poorly suited to turning. Within thirty seconds its temperature rises to a dangerous level and it must stop, whether or not it has eaten. Biologists describe this as an arms race in which neither side can afford to win completely. If cheetahs became reliably successful, the gazelle population would collapse, and the cheetahs would starve soon after. If gazelles escaped every time, the same thing would happen from the other direction. What looks like a contest between a hunter and its victim is, over long periods, a kind of mutual arrangement that neither animal understands and neither could survive without.",
  q:[
  ["What is the main idea of this passage?","Predator and prey are held in a balance that depends on neither side winning",["Predator and prey are held in a balance that depends on neither side winning","Cheetahs are less successful hunters than people believe","Gazelles are better adapted than cheetahs","Speed is the most important trait for survival"],"main"],
  ["Why does the gazelle turn instead of running straight?","Turning attacks the cheetah's main weakness rather than its strength",["Turning attacks the cheetah's main weakness rather than its strength","It hopes to reach a hiding place nearby","It is too tired to keep running forward","It tries to confuse other animals in the herd"],"inference"],
  ["What does the author mean by “neither side can afford to win completely”?","Total victory for either species would destroy both",["Total victory for either species would destroy both","Hunting uses too much energy to be worthwhile","Both animals are protected by law","Neither animal is strong enough to defeat the other"],"vocab"],
  ["Why does the passage begin with the fact that cheetahs fail half the time?","To challenge the reader's assumption that speed determines success",["To challenge the reader's assumption that speed determines success","To argue that cheetahs are poorly evolved","To explain why cheetah numbers are falling","To show that gazelles are unusually clever"],"tone"],
  ["What can we infer about the phrase “neither animal understands”?","The balance is produced by evolution, not by intention",["The balance is produced by evolution, not by intention","Animals are less intelligent than biologists assume","The animals have never encountered each other before","Scientists have not yet explained the behaviour"],"inference"]
  ]},
];
